export enum UserRole {
  EDITOR = 'EDITOR',
  CHIEF_EDITOR = 'CHIEF_EDITOR',
  CHANNEL_OPERATOR = 'CHANNEL_OPERATOR',
  DATA_ANALYST = 'DATA_ANALYST',
  ADMIN = 'ADMIN',
}

export enum ContentStatus {
  DRAFT = 'DRAFT',
  PENDING_REVIEW = 'PENDING_REVIEW',
  IN_REVIEW = 'IN_REVIEW',
  NEEDS_REVISION = 'NEEDS_REVISION',
  APPROVED = 'APPROVED',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
  REJECTED = 'REJECTED',
}

export enum ReviewType {
  FIRST_REVIEW = 'FIRST_REVIEW',
  SECOND_REVIEW = 'SECOND_REVIEW',
  THIRD_REVIEW = 'THIRD_REVIEW',
  FIRST_PROOFREAD = 'FIRST_PROOFREAD',
  SECOND_PROOFREAD = 'SECOND_PROOFREAD',
  THIRD_PROOFREAD = 'THIRD_PROOFREAD',
}

export enum DistributionChannel {
  WEB = 'WEB',
  APP = 'APP',
  WECHAT = 'WECHAT',
  WEIBO = 'WEIBO',
  DOUYIN = 'DOUYIN',
  XIAOHONGSHU = 'XIAOHONGSHU',
  ZHIHU = 'ZHIHU',
}

export enum ReviewStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  NEEDS_REVISION = 'NEEDS_REVISION',
}

export enum DistributionStatus {
  PENDING = 'PENDING',
  SCHEDULED = 'SCHEDULED',
  PUBLISHING = 'PUBLISHING',
  PUBLISHED = 'PUBLISHED',
  FAILED = 'FAILED',
  RETRYING = 'RETRYING',
}

export enum WorkflowStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}
