export enum NotificationType {
  STYLE_CREATED = 'style_created',
  STYLE_STATUS_UPDATED = 'style_status_updated',
  PATTERN_ASSIGNED = 'pattern_assigned',
  PATTERN_SUBMITTED = 'pattern_submitted',
  PATTERN_CONFIRMED = 'pattern_confirmed',
  PATTERN_REJECTED = 'pattern_rejected',
  BOM_GENERATED = 'bom_generated',
  BOM_CONFIRMED = 'bom_confirmed',
  PURCHASE_ORDER_CREATED = 'purchase_order_created',
  PURCHASE_ORDER_UPDATED = 'purchase_order_updated',
  MATERIAL_RECEIVED = 'material_received',
  PRODUCTION_ORDER_ASSIGNED = 'production_order_assigned',
  PRODUCTION_PROGRESS_UPDATED = 'production_progress_updated',
  PRODUCTION_ISSUE_REPORTED = 'production_issue_reported',
  PRODUCTION_ISSUE_RESOLVED = 'production_issue_resolved',
  SHIPMENT_REQUESTED = 'shipment_requested',
  QUALITY_CHECK_COMPLETED = 'quality_check_completed',
  ORDER_COMPLETED = 'order_completed',
  COMMUNICATION_RECEIVED = 'communication_received',
  SYSTEM_ALERT = 'system_alert',
  REMINDER = 'reminder',
}
