export enum StyleStatus {
  DRAFT = 'draft',
  PENDING_PATTERN = 'pending_pattern',
  PATTERN_IN_PROGRESS = 'pattern_in_progress',
  PATTERN_SUBMITTED = 'pattern_submitted',
  PENDING_CONFIRMATION = 'pending_confirmation',
  CONFIRMED = 'confirmed',
  BOM_GENERATED = 'bom_generated',
  PENDING_PURCHASE = 'pending_purchase',
  PURCHASE_IN_PROGRESS = 'purchase_in_progress',
  MATERIAL_READY = 'material_ready',
  PENDING_PRODUCTION = 'pending_production',
  PRODUCTION_IN_PROGRESS = 'production_in_progress',
  PRODUCTION_COMPLETED = 'production_completed',
  SHIPPED = 'shipped',
  COMPLETED = 'completed',
  CANCELLED = 'cancelled',
  ON_HOLD = 'on_hold',
}
