const db = require('../db');

console.log('=== Database Counts ===');
console.log('Users:', db.prepare('SELECT COUNT(*) as c FROM users').get().c);
console.log('Enterprises:', db.prepare('SELECT COUNT(*) as c FROM enterprises').get().c);
console.log('Pending:', db.prepare("SELECT COUNT(*) as c FROM enterprises WHERE qualification_status = 'pending'").get().c);
console.log('Approved:', db.prepare("SELECT COUNT(*) as c FROM enterprises WHERE qualification_status = 'approved'").get().c);
console.log('Rejected:', db.prepare("SELECT COUNT(*) as c FROM enterprises WHERE qualification_status = 'rejected'").get().c);
console.log('Jobs:', db.prepare('SELECT COUNT(*) as c FROM jobs').get().c);
console.log('Applications:', db.prepare('SELECT COUNT(*) as c FROM applications').get().c);
console.log('Audit logs:', db.prepare('SELECT COUNT(*) as c FROM audit_logs').get().c);
console.log('Match scores:', db.prepare('SELECT COUNT(*) as c FROM job_match_scores').get().c);
console.log('Onboarding:', db.prepare('SELECT COUNT(*) as c FROM onboarding_records').get().c);
console.log('');
console.log('=== Pending Enterprises ===');
console.log(db.prepare('SELECT enterprise_name, qualification_status FROM enterprises').all());
console.log('');
console.log('=== Audit Log Actions ===');
console.log(db.prepare('SELECT action, COUNT(*) as c FROM audit_logs GROUP BY action').all());
console.log('');
console.log('=== Sample Job ===');
const job = db.prepare('SELECT id, job_title, salary_min, salary_max, salary_compliance_checked FROM jobs LIMIT 1').get();
console.log(job);
