CREATE TABLE IF NOT EXISTS `api_info` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `api_code` varchar(100) NOT NULL COMMENT 'API编码',
  `api_name` varchar(200) NOT NULL COMMENT 'API名称',
  `api_version` varchar(20) NOT NULL DEFAULT '1.0' COMMENT 'API版本',
  `api_desc` varchar(500) DEFAULT NULL COMMENT 'API描述',
  `request_method` varchar(10) NOT NULL COMMENT '请求方式: GET,POST,PUT,DELETE',
  `request_url` varchar(500) NOT NULL COMMENT '请求URL',
  `dept_code` varchar(50) NOT NULL COMMENT '所属部门编码',
  `dept_name` varchar(100) NOT NULL COMMENT '所属部门名称',
  `datasource_code` varchar(50) NOT NULL COMMENT '数据源编码',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态:0-草稿,1-已发布,2-已下线,3-已废弃',
  `qps_limit` int NOT NULL DEFAULT '100' COMMENT 'QPS限制',
  `need_auth` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否需要鉴权:0-否,1-是',
  `need_desensitize` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否需要脱敏:0-否,1-是',
  `request_param` text COMMENT '请求参数定义(JSON)',
  `response_param` text COMMENT '响应参数定义(JSON)',
  `request_example` text COMMENT '请求示例',
  `response_example` text COMMENT '响应示例',
  `publish_time` datetime DEFAULT NULL COMMENT '发布时间',
  `offline_time` datetime DEFAULT NULL COMMENT '下线时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除:0-否,1-是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_api_code_version` (`api_code`,`api_version`,`deleted`),
  KEY `idx_dept_code` (`dept_code`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='API信息表';

CREATE TABLE IF NOT EXISTS `data_permission` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `api_id` bigint NOT NULL COMMENT 'API ID',
  `api_code` varchar(100) NOT NULL COMMENT 'API编码',
  `role_code` varchar(50) DEFAULT NULL COMMENT '角色编码',
  `role_name` varchar(100) DEFAULT NULL COMMENT '角色名称',
  `dept_code` varchar(50) DEFAULT NULL COMMENT '部门编码',
  `dept_name` varchar(100) DEFAULT NULL COMMENT '部门名称',
  `user_id` varchar(50) DEFAULT NULL COMMENT '用户ID',
  `user_name` varchar(100) DEFAULT NULL COMMENT '用户名称',
  `permission_type` varchar(20) NOT NULL DEFAULT 'role' COMMENT '权限类型: role-角色, dept-部门, user-用户',
  `data_scope` varchar(20) NOT NULL DEFAULT 'all' COMMENT '数据范围: all-全部, dept-本部门, dept_and_child-本部门及下级, self-仅本人, custom-自定义',
  `field_permissions` text COMMENT '字段权限(JSON格式)',
  `can_query` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否可查询:0-否,1-是',
  `can_export` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否可导出:0-否,1-是',
  `row_limit` int DEFAULT NULL COMMENT '行数限制',
  `condition_expression` text COMMENT '自定义条件表达式',
  `priority` int NOT NULL DEFAULT '0' COMMENT '优先级,数字越大优先级越高',
  `status` varchar(2) NOT NULL DEFAULT '1' COMMENT '状态:0-禁用,1-启用',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除:0-否,1-是',
  PRIMARY KEY (`id`),
  KEY `idx_api_id` (`api_id`),
  KEY `idx_api_code` (`api_code`),
  KEY `idx_role_code` (`role_code`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据权限表';

CREATE TABLE IF NOT EXISTS `api_visit_log` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `trace_id` varchar(64) DEFAULT NULL COMMENT '链路追踪ID',
  `api_id` bigint DEFAULT NULL COMMENT 'API ID',
  `api_code` varchar(100) DEFAULT NULL COMMENT 'API编码',
  `api_name` varchar(200) DEFAULT NULL COMMENT 'API名称',
  `request_method` varchar(10) DEFAULT NULL COMMENT '请求方式',
  `request_url` varchar(500) DEFAULT NULL COMMENT '请求URL',
  `request_param` longtext COMMENT '请求参数',
  `response_data` longtext COMMENT '响应数据',
  `client_ip` varchar(50) DEFAULT NULL COMMENT '客户端IP',
  `user_agent` varchar(500) DEFAULT NULL COMMENT '用户代理',
  `user_id` varchar(50) DEFAULT NULL COMMENT '用户ID',
  `user_name` varchar(100) DEFAULT NULL COMMENT '用户名称',
  `dept_code` varchar(50) DEFAULT NULL COMMENT '部门编码',
  `dept_name` varchar(100) DEFAULT NULL COMMENT '部门名称',
  `request_time` datetime DEFAULT NULL COMMENT '请求时间',
  `response_time` datetime DEFAULT NULL COMMENT '响应时间',
  `cost_time` bigint DEFAULT NULL COMMENT '耗时(毫秒)',
  `http_status` int DEFAULT NULL COMMENT 'HTTP状态码',
  `response_code` varchar(20) DEFAULT NULL COMMENT '响应码',
  `response_msg` varchar(500) DEFAULT NULL COMMENT '响应消息',
  `success` tinyint(1) DEFAULT NULL COMMENT '是否成功:0-否,1-是',
  `blockchain_hash` varchar(256) DEFAULT NULL COMMENT '区块链存证哈希',
  `error_msg` text COMMENT '错误信息',
  `extend_info` text COMMENT '扩展信息(JSON)',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除:0-否,1-是',
  PRIMARY KEY (`id`),
  KEY `idx_trace_id` (`trace_id`),
  KEY `idx_api_code` (`api_code`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_request_time` (`request_time`),
  KEY `idx_success` (`success`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='API访问日志表';

CREATE TABLE IF NOT EXISTS `data_desensitize_rule` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `rule_code` varchar(50) NOT NULL COMMENT '规则编码',
  `rule_name` varchar(100) NOT NULL COMMENT '规则名称',
  `desensitize_type` varchar(50) NOT NULL COMMENT '脱敏类型: phone-手机号, id_card-身份证, bank_card-银行卡, email-邮箱, name-姓名, custom-自定义',
  `desensitize_strategy` varchar(20) NOT NULL DEFAULT 'mask' COMMENT '脱敏策略: mask-掩码, hash-哈希, replace-替换, truncate-截断, encrypt-加密',
  `field_name` varchar(100) DEFAULT NULL COMMENT '字段名',
  `pattern` varchar(500) DEFAULT NULL COMMENT '正则表达式',
  `mask_char` varchar(1) DEFAULT '*' COMMENT '掩码字符',
  `keep_left` int DEFAULT '3' COMMENT '左侧保留位数',
  `keep_right` int DEFAULT '4' COMMENT '右侧保留位数',
  `replace_value` varchar(100) DEFAULT NULL COMMENT '替换值',
  `encrypt_key` varchar(256) DEFAULT NULL COMMENT '加密密钥',
  `hash_algorithm` varchar(20) DEFAULT 'SHA-256' COMMENT '哈希算法',
  `api_id` bigint DEFAULT NULL COMMENT '关联API ID(空表示全局规则)',
  `api_code` varchar(100) DEFAULT NULL COMMENT '关联API编码',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序',
  `enabled` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否启用:0-否,1-是',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除:0-否,1-是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_rule_code` (`rule_code`,`deleted`),
  KEY `idx_api_id` (`api_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据脱敏规则表';

INSERT INTO `data_desensitize_rule` (`id`, `rule_code`, `rule_name`, `desensitize_type`, `desensitize_strategy`, `field_name`, `pattern`, `keep_left`, `keep_right`, `sort`, `enabled`, `create_time`) VALUES
(1, 'global-phone', '全局手机号脱敏', 'phone', 'mask', 'phone', '^1[3-9]\\d{9}$', 3, 4, 1, 1, NOW()),
(2, 'global-id-card', '全局身份证脱敏', 'id_card', 'mask', 'idCard', '^[1-9]\\d{5}(18|19|20)\\d{2}(0[1-9]|1[0-2])(0[1-9]|[12]\\d|3[01])\\d{3}[\\dXx]$', 3, 4, 2, 1, NOW()),
(3, 'global-bank-card', '全局银行卡脱敏', 'bank_card', 'mask', 'bankCard', '^\\d{16,19}$', 4, 4, 3, 1, NOW()),
(4, 'global-email', '全局邮箱脱敏', 'email', 'mask', 'email', '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$', 2, 0, 4, 1, NOW()),
(5, 'global-name', '全局姓名脱敏', 'name', 'mask', 'name', '^[\\u4e00-\\u9fa5]{2,4}$', 1, 0, 5, 1, NOW());
