import request from '../utils/request';

export const getDashboard = () => request.get('/admin/dashboard');
export const getUsers = (params) => request.get('/admin/users', { params });
export const getUserDetail = (id) => request.get(`/admin/users/${id}`);
export const updateUserStatus = (id, data) => request.put(`/admin/users/${id}/status`, data);
export const getCards = (params) => request.get('/admin/cards', { params });
export const updateCardStatus = (id, data) => request.put(`/admin/cards/${id}/status`, data);
export const getTransactions = (params) => request.get('/admin/transactions', { params });
export const getTransactionDetail = (id) => request.get(`/admin/transactions/${id}`);
export const getBlockedTransactions = (params) => request.get('/admin/risk/blocked', { params });
export const resolveBlockedTransaction = (id, data) => request.post(`/admin/risk/blocked/${id}/resolve`, data);
export const getRenewals = (params) => request.get('/admin/renewals', { params });
export const reviewRenewal = (id, data) => request.post(`/admin/renewals/${id}/review`, data);
export const getRegions = () => request.get('/admin/regions');
export const getAdminRoutes = () => request.get('/admin/routes');
export const createRoute = (data) => request.post('/admin/routes', data);
export const updateRoute = (id, data) => request.put(`/admin/routes/${id}`, data);
export const getAdminProducts = () => request.get('/admin/products');
export const createProduct = (data) => request.post('/admin/products', data);
export const updateProduct = (id, data) => request.put(`/admin/products/${id}`, data);
export const getOperationLogs = (params) => request.get('/admin/operation-logs', { params });
export const getAdmins = () => request.get('/admin/admins');
export const createAdmin = (data) => request.post('/admin/admins', data);
