export enum UserRole {
  APPLICANT = 'APPLICANT',
  COURIER = 'COURIER',
  APPROVER = 'APPROVER',
  CITY_OPERATOR = 'CITY_OPERATOR',
  PROVINCE_ADMIN = 'PROVINCE_ADMIN',
  THIRD_PARTY_SERVICE = 'THIRD_PARTY_SERVICE',
}

export enum IdentityVerifyStatus {
  UNVERIFIED = 'UNVERIFIED',
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  FAILED = 'FAILED',
}

export enum OrderType {
  HK_MACAO_VISA = 'HK_MACAO_VISA',
  TAIWAN_VISA = 'TAIWAN_VISA',
  ID_CARD_REPLACEMENT = 'ID_CARD_REPLACEMENT',
  VIOLATION_PAYMENT = 'VIOLATION_PAYMENT',
  VEHICLE_INSPECTION = 'VEHICLE_INSPECTION',
}

export enum OrderStatus {
  CREATED = 'CREATED',
  PENDING_PICKUP = 'PENDING_PICKUP',
  COURIER_ASSIGNED = 'COURIER_ASSIGNED',
  PICKED_UP = 'PICKED_UP',
  OCR_PROCESSING = 'OCR_PROCESSING',
  PRE_REVIEW = 'PRE_REVIEW',
  PRE_REVIEW_PASSED = 'PRE_REVIEW_PASSED',
  PRE_REVIEW_FAILED = 'PRE_REVIEW_FAILED',
  SUBMITTED_FOR_APPROVAL = 'SUBMITTED_FOR_APPROVAL',
  APPROVING = 'APPROVING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CERTIFICATE_PRINTING = 'CERTIFICATE_PRINTING',
  PENDING_DELIVERY = 'PENDING_DELIVERY',
  IN_DELIVERY = 'IN_DELIVERY',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum PaymentStatus {
  UNPAID = 'UNPAID',
  PENDING = 'PENDING',
  PAID = 'PAID',
  REFUNDING = 'REFUNDING',
  REFUNDED = 'REFUNDED',
  FAILED = 'FAILED',
}

export enum PaymentChannel {
  UNIONPAY = 'UNIONPAY',
  WECHAT_PAY = 'WECHAT_PAY',
  ALIPAY = 'ALIPAY',
}

export enum CourierTaskStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  EN_ROUTE = 'EN_ROUTE',
  ARRIVED = 'ARRIVED',
  PICKED = 'PICKED',
  DELIVERING = 'DELIVERING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum OcrStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  NEED_MANUAL_REVIEW = 'NEED_MANUAL_REVIEW',
}

export enum AlertLevel {
  INFO = 'INFO',
  WARNING = 'WARNING',
  DANGER = 'DANGER',
  CRITICAL = 'CRITICAL',
}

export enum AlertType {
  SLA_WARNING = 'SLA_WARNING',
  SLA_BREACH = 'SLA_BREACH',
  PAYMENT_EXCEPTION = 'PAYMENT_EXCEPTION',
  OCR_FAILURE = 'OCR_FAILURE',
  APPROVAL_DELAY = 'APPROVAL_DELAY',
  COURIER_DELAY = 'COURIER_DELAY',
}

export enum VisaType {
  HK_G_SIGN = 'HK_G_SIGN',
  HK_L_SIGN = 'HK_L_SIGN',
  HK_T_SIGN = 'HK_T_SIGN',
  HK_S_SIGN = 'HK_S_SIGN',
  HK_D_SIGN = 'HK_D_SIGN',
  MACAO_G_SIGN = 'MACAO_G_SIGN',
  MACAO_L_SIGN = 'MACAO_L_SIGN',
  HK_MACAO_PERSONAL = 'HK_MACAO_PERSONAL',
  HK_MACAO_BUSINESS = 'HK_MACAO_BUSINESS',
  HK_MACAO_TEAM = 'HK_MACAO_TEAM',
  HK_MACAO_TRANSIT = 'HK_MACAO_TRANSIT',
  TAIWAN_G_SIGN = 'TAIWAN_G_SIGN',
  TAIWAN_L_SIGN = 'TAIWAN_L_SIGN',
  TAIWAN_PERSONAL = 'TAIWAN_PERSONAL',
  TAIWAN_BUSINESS = 'TAIWAN_BUSINESS',
  TAIWAN_TEAM = 'TAIWAN_TEAM',
}

export enum ViolationSource {
  TRAFFIC_12123 = 'TRAFFIC_12123',
  MINISTRY_POLICE_DB = 'MINISTRY_POLICE_DB',
  CITY_TRAFFIC_BUREAU = 'CITY_TRAFFIC_BUREAU',
  THIRD_PARTY_AGGREGATOR = 'THIRD_PARTY_AGGREGATOR',
}

export enum EmsShipmentStatus {
  CREATED = 'CREATED',
  PICKED_UP = 'PICKED_UP',
  IN_TRANSIT = 'IN_TRANSIT',
  ARRIVED_AT_CITY = 'ARRIVED_AT_CITY',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
  RETURNED = 'RETURNED',
}

export enum ApprovalStatus {
  PENDING = 'PENDING',
  APPROVING = 'APPROVING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  RETURNED_FOR_SUPPLEMENT = 'RETURNED_FOR_SUPPLEMENT',
}

export enum IdCardApplicationType {
  LOST_REPLACEMENT = 'LOST_REPLACEMENT',
  EXPIRED_REPLACEMENT = 'EXPIRED_REPLACEMENT',
  DAMAGED_REPLACEMENT = 'DAMAGED_REPLACEMENT',
  INFORMATION_CHANGE = 'INFORMATION_CHANGE',
}

export enum InspectionStatus {
  PENDING = 'PENDING',
  PICKED_UP = 'PICKED_UP',
  TESTING = 'TESTING',
  PASSED = 'PASSED',
  FAILED = 'FAILED',
  STICKER_MAILED = 'STICKER_MAILED',
  COMPLETED = 'COMPLETED',
}

export enum FundTransactionType {
  SERVICE_FEE_COLLECT = 'SERVICE_FEE_COLLECT',
  GOVERNMENT_FEE_COLLECT = 'GOVERNMENT_FEE_COLLECT',
  COURIER_FEE_COLLECT = 'COURIER_FEE_COLLECT',
  SERVICE_FEE_SETTLE = 'SERVICE_FEE_SETTLE',
  GOVERNMENT_FEE_TRANSFER = 'GOVERNMENT_FEE_TRANSFER',
  COURIER_FEE_SETTLE = 'COURIER_FEE_SETTLE',
  REFUND = 'REFUND',
}

export enum FundAccountType {
  REGULATORY = 'REGULATORY',
  SERVICE_REVENUE = 'SERVICE_REVENUE',
  GOVERNMENT_PAYABLE = 'GOVERNMENT_PAYABLE',
  COURIER_PAYABLE = 'COURIER_PAYABLE',
}

export const GD_CITIES = [
  '广州市', '深圳市', '珠海市', '汕头市', '佛山市',
  '韶关市', '湛江市', '肇庆市', '江门市', '茂名市',
  '惠州市', '梅州市', '汕尾市', '河源市', '阳江市',
  '清远市', '东莞市', '中山市', '潮州市', '揭阳市', '云浮市',
] as const;

export type GdCity = typeof GD_CITIES[number];

export interface GeoLocation {
  latitude: number;
  longitude: number;
  address?: string;
}

export interface PaginationParams {
  page: number;
  pageSize: number;
}

export interface ApiResponse<T = unknown> {
  code: number;
  message: string;
  data?: T;
  timestamp: number;
  traceId?: string;
}

export interface PaginatedResponse<T> {
  list: T[];
  total: number;
  page: number;
  pageSize: number;
}

export interface JWTPayload {
  userId: string;
  role: UserRole;
  city?: GdCity;
  realNameVerified: boolean;
}
