let data = {
  users: [
    {
      _id: '1',
      username: 'demo',
      nickname: '惠州小市民',
      password: '$2a$10$demo',
      avatar: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=friendly%20user%20avatar%20portrait&image_size=square',
      points: 520,
      level: 3,
      isAdmin: false,
      phone: '138****8888',
      createdAt: '2024-01-01T00:00:00Z',
      lastLoginAt: new Date().toISOString(),
    },
    {
      _id: '2',
      username: 'admin',
      nickname: '管理员',
      password: '$2a$10$admin',
      avatar: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=admin%20user%20avatar%20professional&image_size=square',
      points: 9999,
      level: 10,
      isAdmin: true,
      phone: '139****9999',
      createdAt: '2023-12-01T00:00:00Z',
      lastLoginAt: new Date().toISOString(),
    },
  ],
  posts: [
    {
      _id: 'p1',
      userId: '1',
      title: '西湖景区这几天游客真多啊',
      content: '周末去西湖逛了一圈，发现游客比平时多了好多，尤其是泗州塔那边人挤人。不过景色确实很美，木棉花都开了，拍照特别好看。建议大家可以错峰出行，或者早一点过去。',
      category: 'life',
      location: { lat: 23.0837, lng: 114.4122, address: '惠州西湖景区', district: '惠城区' },
      media: [
        { type: 'image', url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=huizhou%20west%20lake%20beautiful%20scenery%20pagoda&image_size=square_hd' },
        { type: 'image', url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=huizhou%20west%20lake%20boat%20tour&image_size=square_hd' },
      ],
      status: 'approved',
      sentiment: 'positive',
      likes: 128,
      comments: 32,
      views: 1256,
      createdAt: '2024-01-15T10:30:00Z',
      updatedAt: '2024-01-15T10:30:00Z',
    },
    {
      _id: 'p2',
      userId: '1',
      title: '河南岸这边修路堵得厉害，建议绕行',
      content: '今天早高峰河南岸花边岭那边堵死了，好像是修路导致的。本来20分钟的路走了快一个小时。建议大家近期尽量绕行，或者选择公共交通出行。',
      category: 'traffic',
      location: { lat: 23.0761, lng: 114.4158, address: '河南岸花边岭', district: '惠城区' },
      media: [],
      status: 'approved',
      sentiment: 'negative',
      likes: 56,
      comments: 18,
      views: 890,
      createdAt: '2024-01-14T08:15:00Z',
      updatedAt: '2024-01-14T08:15:00Z',
    },
    {
      _id: 'p3',
      userId: '1',
      title: '发现一家超好吃的客家菜馆！',
      content: '在桥东水东街那边发现一家新开的客家菜馆，味道真的很正宗！盐焗鸡皮脆肉嫩，梅菜扣肉肥而不腻，酿豆腐也很入味。价格也不贵，人均60左右。强烈推荐给大家！',
      category: 'life',
      location: { lat: 23.0912, lng: 114.4203, address: '桥东水东街', district: '惠城区' },
      media: [
        { type: 'image', url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=hakka%20cuisine%20delicious%20food&image_size=square_hd' },
      ],
      status: 'approved',
      sentiment: 'positive',
      likes: 234,
      comments: 45,
      views: 2100,
      createdAt: '2024-01-13T19:20:00Z',
      updatedAt: '2024-01-13T19:20:00Z',
    },
    {
      _id: 'p4',
      userId: '1',
      title: '大亚湾海边的日落太美了',
      content: '周末去了大亚湾黄金海岸，傍晚的日落真的超级美！海浪拍打着沙滩，天空被染成了橙红色。人也不是很多，很适合放松心情。就是路程有点远，开车要一个多小时。',
      category: 'culture',
      location: { lat: 22.7036, lng: 114.5639, address: '大亚湾黄金海岸', district: '大亚湾区' },
      media: [
        { type: 'image', url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=daya%20bay%20sunset%20beach%20beautiful&image_size=square_hd' },
        { type: 'image', url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=golden%20sand%20beach%20waves%20sunset&image_size=square_hd' },
        { type: 'image', url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=seaside%20sunset%20silhouette%20romantic&image_size=square_hd' },
      ],
      status: 'approved',
      sentiment: 'positive',
      likes: 356,
      comments: 67,
      views: 3450,
      createdAt: '2024-01-12T18:45:00Z',
      updatedAt: '2024-01-12T18:45:00Z',
    },
    {
      _id: 'p5',
      userId: '1',
      title: '小区门口的路灯坏了好几天了',
      content: '我们小区门口的路灯坏了快一周了，晚上黑漆漆的很不安全。物业说已经报上去了，但一直没人来修。不知道这种情况该找哪个部门反应？',
      category: 'environment',
      location: { lat: 23.1816, lng: 114.2878, address: '罗阳镇某小区', district: '博罗县' },
      media: [],
      status: 'pending',
      sentiment: 'negative',
      likes: 12,
      comments: 5,
      views: 156,
      createdAt: '2024-01-16T09:00:00Z',
      updatedAt: '2024-01-16T09:00:00Z',
    },
    {
      _id: 'p6',
      userId: '1',
      title: '仲恺这家工厂深夜偷排废气',
      content: '最近这段时间，一到深夜就能闻到一股刺鼻的味道，好像是附近哪家工厂在偷排废气。窗户都不敢开，太难受了。希望有关部门能管一管！',
      category: 'environment',
      location: { lat: 22.9961, lng: 114.3286, address: '仲恺高新区', district: '仲恺高新区' },
      media: [],
      status: 'pending',
      sentiment: 'negative',
      likes: 89,
      comments: 23,
      views: 567,
      createdAt: '2024-01-16T23:30:00Z',
      updatedAt: '2024-01-16T23:30:00Z',
    },
    {
      _id: 'p7',
      userId: '1',
      title: '罗浮山徒步路线推荐',
      content: '周末去了罗浮山徒步，走的是飞云顶路线，风景真的超赞！一路上有溪水、竹林、瀑布，山顶还能看到云海。建议大家早点出发，全程大概需要6-7小时，记得带够水和零食。',
      category: 'culture',
      location: { lat: 23.2876, lng: 114.0123, address: '罗浮山风景区', district: '博罗县' },
      media: [
        { type: 'image', url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=luofu%20mountain%20hiking%20scenery&image_size=square_hd' },
      ],
      status: 'approved',
      sentiment: 'positive',
      likes: 178,
      comments: 42,
      views: 1890,
      createdAt: '2024-01-11T16:00:00Z',
      updatedAt: '2024-01-11T16:00:00Z',
    },
  ],
  circles: [
    {
      _id: 'c1',
      name: '惠州摄影爱好者',
      category: 'photography',
      description: '记录惠州的美好瞬间，分享摄影技巧与作品。欢迎所有喜欢摄影的朋友加入！',
      avatar: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=photography%20club%20camera%20logo&image_size=square',
      coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=huizhou%20west%20lake%20landscape%20photography&image_size=landscape_16_9',
      memberCount: 1280,
      postCount: 3560,
      adminIds: ['2'],
      members: ['1', '2'],
      createdAt: '2023-10-01T00:00:00Z',
    },
    {
      _id: 'c2',
      name: '惠州亲子乐园',
      category: 'parenting',
      description: '惠州宝爸宝妈交流平台，分享育儿经验与亲子活动，一起陪伴孩子成长。',
      avatar: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=parenting%20family%20kids%20logo&image_size=square',
      coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=happy%20family%20park%20children&image_size=landscape_16_9',
      memberCount: 2560,
      postCount: 8900,
      adminIds: ['2'],
      members: ['1'],
      createdAt: '2023-09-15T00:00:00Z',
    },
    {
      _id: 'c3',
      name: '惠州美食探索',
      category: 'food',
      description: '发现惠州美食，分享地道客家菜与海鲜。吃货们的聚集地！',
      avatar: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=food%20delicious%20restaurant%20logo&image_size=square',
      coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=huizhou%20seafood%20hakka%20cuisine&image_size=landscape_16_9',
      memberCount: 3200,
      postCount: 12000,
      adminIds: ['2'],
      members: ['1'],
      createdAt: '2023-08-20T00:00:00Z',
    },
    {
      _id: 'c4',
      name: '惠州户外探险',
      category: 'outdoor',
      description: '徒步、登山、露营，探索惠州的自然之美。每周都有活动！',
      avatar: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=outdoor%20hiking%20mountain%20logo&image_size=square',
      coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=luofu%20mountain%20hiking%20nature&image_size=landscape_16_9',
      memberCount: 1890,
      postCount: 4500,
      adminIds: ['2'],
      members: ['1'],
      createdAt: '2023-07-10T00:00:00Z',
    },
    {
      _id: 'c5',
      name: '惠州健身达人',
      category: 'fitness',
      description: '运动健身交流，打卡锻炼，共同进步。坚持就是胜利！',
      avatar: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=fitness%20gym%20workout%20logo&image_size=square',
      coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=fitness%20gym%20workout%20people&image_size=landscape_16_9',
      memberCount: 1560,
      postCount: 3200,
      adminIds: ['2'],
      members: [],
      createdAt: '2023-11-05T00:00:00Z',
    },
    {
      _id: 'c6',
      name: '惠州科技前沿',
      category: 'tech',
      description: '科技爱好者聚集地，分享数码产品与技术，一起探讨科技未来。',
      avatar: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=technology%20digital%20innovation%20logo&image_size=square',
      coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=technology%20digital%20future%20city&image_size=landscape_16_9',
      memberCount: 980,
      postCount: 2100,
      adminIds: ['2'],
      members: [],
      createdAt: '2023-12-01T00:00:00Z',
    },
    {
      _id: 'c7',
      name: '惠州艺术空间',
      category: 'art',
      description: '绘画、书法、音乐等艺术交流平台，陶冶情操，发现生活之美。',
      avatar: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=art%20painting%20creativity%20logo&image_size=square',
      coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=art%20painting%20gallery%20creative&image_size=landscape_16_9',
      memberCount: 720,
      postCount: 1800,
      adminIds: ['2'],
      members: [],
      createdAt: '2023-10-20T00:00:00Z',
    },
  ],
  activities: [
    {
      _id: 'a1',
      circleId: 'c1',
      title: '西湖春季摄影采风活动',
      description: '趁着春暖花开，我们组织一次西湖摄影采风活动。早上6点集合，拍摄西湖日出和晨雾。活动免费，欢迎所有摄影爱好者参加，器材自备。',
      coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=west%20lake%20sunrise%20photography%20spring&image_size=landscape_16_9',
      location: { lat: 23.0837, lng: 114.4122, address: '惠州西湖北门', district: '惠城区' },
      startTime: '2024-02-10T06:00:00Z',
      endTime: '2024-02-10T10:00:00Z',
      maxParticipants: 30,
      participantCount: 18,
      participants: ['1', '2'],
      fee: 0,
      organizerId: '2',
      status: 'upcoming',
      results: [],
      createdAt: '2024-01-10T00:00:00Z',
    },
    {
      _id: 'a2',
      circleId: 'c4',
      title: '罗浮山飞云顶徒步穿越',
      description: '本周六罗浮山徒步活动，路线：酥醪观-飞云顶-拨云寺，全程约15公里。难度中等，建议有一定徒步基础的朋友参加。自带午餐和水，统一购买保险。',
      coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=luofu%20mountain%20hiking%20adventure&image_size=landscape_16_9',
      location: { lat: 23.2876, lng: 114.0123, address: '罗浮山酥醪观', district: '博罗县' },
      startTime: '2024-01-20T07:30:00Z',
      endTime: '2024-01-20T18:00:00Z',
      maxParticipants: 25,
      participantCount: 22,
      participants: ['1'],
      fee: 68,
      organizerId: '2',
      status: 'upcoming',
      results: [],
      createdAt: '2024-01-08T00:00:00Z',
    },
    {
      _id: 'a3',
      circleId: 'c2',
      title: '亲子DIY风筝活动',
      description: '周末带上孩子一起动手做风筝！我们提供所有材料，专业老师指导。做完的风筝可以直接在草坪上放飞。适合3-12岁小朋友，需家长陪同。',
      coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=kids%20kite%20DIY%20family%20activity&image_size=landscape_16_9',
      location: { lat: 23.0750, lng: 114.4000, address: '东江公园', district: '惠城区' },
      startTime: '2024-01-21T09:00:00Z',
      endTime: '2024-01-21T11:30:00Z',
      maxParticipants: 20,
      participantCount: 15,
      participants: [],
      fee: 39,
      organizerId: '2',
      status: 'upcoming',
      results: [],
      createdAt: '2024-01-05T00:00:00Z',
    },
    {
      _id: 'a4',
      circleId: 'c3',
      title: '桥东美食探店团',
      description: '一起去桥东水东街探店！我们精选了5家特色小店，有客家小吃、糖水铺、老字号餐馆等。AA制，人均约100元。吃货们不要错过！',
      coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=street%20food%20tour%20hakka%20snacks&image_size=landscape_16_9',
      location: { lat: 23.0912, lng: 114.4203, address: '桥东水东街', district: '惠城区' },
      startTime: '2024-01-27T11:00:00Z',
      endTime: '2024-01-27T14:00:00Z',
      maxParticipants: 15,
      participantCount: 10,
      participants: ['1'],
      fee: 0,
      organizerId: '2',
      status: 'upcoming',
      results: [],
      createdAt: '2024-01-12日T00:00:00Z',
    },
  ],
  coupons: [
    {
      _id: 'cp1',
      merchantName: '华贸天地',
      title: '满200减50代金券',
      description: '全场通用，可与其他优惠叠加',
      discount: '满200减50',
      pointsRequired: 500,
      image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=shopping%20mall%20coupon%20voucher&image_size=square',
      validUntil: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
      stock: 200,
      redeemedCount: 56,
    },
    {
      _id: 'cp2',
      merchantName: '万达影城',
      title: '电影票5折优惠券',
      description: '普通厅通兑，不限场次',
      discount: '5折',
      pointsRequired: 300,
      image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cinema%20movie%20ticket%20coupon&image_size=square',
      validUntil: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
      stock: 500,
      redeemedCount: 128,
    },
    {
      _id: 'cp3',
      merchantName: '真功夫',
      title: '免费升级套餐券',
      description: '任意套餐免费升级大份',
      discount: '免费升级',
      pointsRequired: 100,
      image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=fast%20food%20restaurant%20coupon&image_size=square',
      validUntil: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
      stock: 1000,
      redeemedCount: 234,
    },
    {
      _id: 'cp4',
      merchantName: '惠州西湖景区',
      title: '游船8折优惠券',
      description: '画舫游船票8折优惠',
      discount: '8折',
      pointsRequired: 200,
      image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=west%20lake%20boat%20tour%20coupon&image_size=square',
      validUntil: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
      stock: 300,
      redeemedCount: 89,
    },
    {
      _id: 'cp5',
      merchantName: '星巴克',
      title: '买一送一券',
      description: '指定饮品买一送一',
      discount: '买一送一',
      pointsRequired: 400,
      image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=coffee%20starbucks%20coupon%20voucher&image_size=square',
      validUntil: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
      stock: 150,
      redeemedCount: 67,
    },
  ],
  donations: [
    {
      _id: 'd1',
      title: '山区儿童图书捐赠计划',
      description: '为惠州山区学校捐赠图书，让孩子们有更多阅读机会，点亮他们的童年。',
      targetAmount: 100000,
      currentAmount: 35600,
      pointsRequired: 100,
      image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=children%20reading%20books%20donation&image_size=square',
      donorCount: 356,
    },
    {
      _id: 'd2',
      title: '环卫工人爱心早餐',
      description: '为惠州环卫工人提供爱心早餐，温暖城市美容师。每一份早餐都是一份关怀。',
      targetAmount: 50000,
      currentAmount: 28900,
      pointsRequired: 50,
      image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=street%20cleaner%20breakfast%20charity&image_size=square',
      donorCount: 578,
    },
    {
      _id: 'd3',
      title: '流浪动物救助基金',
      description: '救助惠州流浪猫狗，提供食物、医疗和领养服务。每一份爱心都很重要。',
      targetAmount: 80000,
      currentAmount: 42300,
      pointsRequired: 80,
      image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=stray%20cat%20dog%20rescue%20charity&image_size=square',
      donorCount: 528,
    },
  ],
  pointRecords: [
    {
      _id: 'pr1',
      userId: '1',
      amount: 5,
      type: 'earn',
      reason: '每日登录',
      relatedId: null,
      relatedType: 'login',
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'pr2',
      userId: '1',
      amount: 10,
      type: 'earn',
      reason: '发布爆料',
      relatedId: 'p5',
      relatedType: 'post',
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      _id: 'pr3',
      userId: '1',
      amount: 5,
      type: 'earn',
      reason: '参加活动',
      relatedId: 'a2',
      relatedType: 'activity',
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      _id: 'pr4',
      userId: '1',
      amount: 300,
      type: 'spend',
      reason: '兑换优惠券: 电影票5折优惠券',
      relatedId: 'cp2',
      relatedType: 'coupon',
      createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      _id: 'pr5',
      userId: '1',
      amount: 100,
      type: 'spend',
      reason: '公益捐赠: 山区儿童图书捐赠计划',
      relatedId: 'd1',
      relatedType: 'donation',
      createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      _id: 'pr6',
      userId: '1',
      amount: 10,
      type: 'earn',
      reason: '公益捐赠荣誉积分',
      relatedId: 'd1',
      relatedType: 'donation_bonus',
      createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
};

let nextId = 100;

export const inMemoryDB = {
  get users() { return data.users; },
  get posts() { return data.posts; },
  get circles() { return data.circles; },
  get activities() { return data.activities; },
  get coupons() { return data.coupons; },
  get donations() { return data.donations; },
  get pointRecords() { return data.pointRecords; },
  
  addUser(user) {
    const newUser = { ...user, _id: String(nextId++) };
    data.users.push(newUser);
    return newUser;
  },
  
  addPost(post) {
    const newPost = { ...post, _id: String(nextId++) };
    data.posts.unshift(newPost);
    return newPost;
  },
  
  updatePost(id, updates) {
    const index = data.posts.findIndex(p => p._id === id);
    if (index !== -1) {
      data.posts[index] = { ...data.posts[index], ...updates };
      return data.posts[index];
    }
    return null;
  },
  
  addPointRecord(record) {
    const newRecord = { ...record, _id: String(nextId++) };
    data.pointRecords.unshift(newRecord);
    return newRecord;
  },
  
  updateUserPoints(userId, amount) {
    const user = data.users.find(u => u._id === userId);
    if (user) {
      user.points += amount;
      return user;
    }
    return null;
  },
  
  findUserById(id) {
    return data.users.find(u => u._id === id);
  },
  
  findUserByUsername(username) {
    return data.users.find(u => u.username === username);
  },
};

export default inMemoryDB;
