const { v4: uuidv4 } = require('uuid');

const mockUsers = [
  {
    id: uuidv4(),
    username: 'admin',
    email: 'admin@example.com',
    phone: '13800138000',
    nickname: '管理员',
    user_type: 'admin',
    status: 'active',
    Roles: [{ code: 'super_admin' }]
  },
  {
    id: uuidv4(),
    username: 'test',
    email: 'test@example.com',
    phone: '13800138001',
    nickname: '测试用户',
    user_type: 'member',
    status: 'active',
    Roles: [{ code: 'member' }]
  }
];

const mockProducts = [
  {
    id: uuidv4(),
    title: '智能旗舰手机 Pro Max',
    code: 'PHONE-001',
    summary: '最新旗舰智能手机，搭载最新处理器',
    description: '这是智能旗舰手机 Pro Max 的详细描述。产品特性包括高性能、高品质、优质服务等。',
    price: 6999,
    original_price: 8399,
    stock: 100,
    unit: '台',
    is_recommended: true,
    is_new: true,
    is_hot: true,
    status: 'active',
    view_count: 1250,
    category: { id: uuidv4(), name: '智能手机' },
    publish_at: new Date().toISOString(),
    created_at: new Date().toISOString()
  },
  {
    id: uuidv4(),
    title: '轻薄商务笔记本电脑',
    code: 'LAPTOP-001',
    summary: '轻薄便携，商务办公首选',
    description: '这是轻薄商务笔记本电脑的详细描述。产品特性包括高性能、高品质、优质服务等。',
    price: 8999,
    original_price: 10799,
    stock: 50,
    unit: '台',
    is_recommended: true,
    is_new: false,
    is_hot: false,
    status: 'active',
    view_count: 890,
    category: { id: uuidv4(), name: '笔记本电脑' },
    publish_at: new Date().toISOString(),
    created_at: new Date().toISOString()
  },
  {
    id: uuidv4(),
    title: '高清办公投影仪',
    code: 'PROJ-001',
    summary: '高清画质，会议必备',
    description: '这是高清办公投影仪的详细描述。产品特性包括高性能、高品质、优质服务等。',
    price: 4999,
    original_price: 5999,
    stock: 30,
    unit: '台',
    is_recommended: false,
    is_new: false,
    is_hot: true,
    status: 'active',
    view_count: 650,
    category: { id: uuidv4(), name: '投影仪' },
    publish_at: new Date().toISOString(),
    created_at: new Date().toISOString()
  },
  {
    id: uuidv4(),
    title: '无线彩色打印机',
    code: 'PRINT-001',
    summary: '无线打印，高效办公',
    description: '这是无线彩色打印机的详细描述。产品特性包括高性能、高品质、优质服务等。',
    price: 2999,
    original_price: 3599,
    stock: 80,
    unit: '台',
    is_recommended: false,
    is_new: true,
    is_hot: false,
    status: 'active',
    view_count: 420,
    category: { id: uuidv4(), name: '打印机' },
    publish_at: new Date().toISOString(),
    created_at: new Date().toISOString()
  },
  {
    id: uuidv4(),
    title: '专业平板电脑',
    code: 'TABLET-001',
    summary: '专业生产力工具',
    description: '这是专业平板电脑的详细描述。产品特性包括高性能、高品质、优质服务等。',
    price: 3999,
    original_price: 4799,
    stock: 60,
    unit: '台',
    is_recommended: true,
    is_new: false,
    is_hot: false,
    status: 'active',
    view_count: 780,
    category: { id: uuidv4(), name: '平板电脑' },
    publish_at: new Date().toISOString(),
    created_at: new Date().toISOString()
  },
  {
    id: uuidv4(),
    title: '智能手表 Ultra',
    code: 'WATCH-001',
    summary: '运动健康监测，智能生活助手',
    description: '这是智能手表 Ultra 的详细描述。产品特性包括高性能、高品质、优质服务等。',
    price: 2999,
    original_price: 3599,
    stock: 150,
    unit: '台',
    is_recommended: false,
    is_new: true,
    is_hot: true,
    status: 'active',
    view_count: 2100,
    category: { id: uuidv4(), name: '智能穿戴' },
    publish_at: new Date().toISOString(),
    created_at: new Date().toISOString()
  },
  {
    id: uuidv4(),
    title: '无线蓝牙耳机 Pro',
    code: 'HEADPHONE-001',
    summary: '主动降噪，沉浸体验',
    description: '这是无线蓝牙耳机 Pro 的详细描述。产品特性包括高性能、高品质、优质服务等。',
    price: 1299,
    original_price: 1599,
    stock: 200,
    unit: '台',
    is_recommended: true,
    is_new: false,
    is_hot: true,
    status: 'active',
    view_count: 3500,
    category: { id: uuidv4(), name: '音频设备' },
    publish_at: new Date().toISOString(),
    created_at: new Date().toISOString()
  },
  {
    id: uuidv4(),
    title: '智能空气净化器',
    code: 'AIR-001',
    summary: '高效净化，健康呼吸',
    description: '这是智能空气净化器的详细描述。产品特性包括高性能、高品质、优质服务等。',
    price: 2499,
    original_price: 2999,
    stock: 40,
    unit: '台',
    is_recommended: false,
    is_new: true,
    is_hot: false,
    status: 'active',
    view_count: 920,
    category: { id: uuidv4(), name: '智能家居' },
    publish_at: new Date().toISOString(),
    created_at: new Date().toISOString()
  }
];

const mockNews = [
  {
    id: uuidv4(),
    title: '公司2024年度表彰大会圆满举行',
    subtitle: '表彰先进，激励前行',
    summary: '公司年度表彰大会在总部隆重举行，表彰了过去一年中表现优秀的团队和个人。',
    content: '<p>公司年度表彰大会在总部隆重举行，表彰了过去一年中表现优秀的团队和个人。</p><p>这是新闻的详细内容部分。在这里可以详细介绍新闻的背景、经过和影响等信息。</p>',
    cover_image: '',
    author: '管理员',
    source: '公司官网',
    keywords: '表彰大会,年度总结',
    is_top: true,
    is_recommended: true,
    is_hot: false,
    status: 'published',
    view_count: 1580,
    category: { id: uuidv4(), name: '公司动态' },
    publish_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    created_at: new Date(Date.now() - 86400000 * 2).toISOString()
  },
  {
    id: uuidv4(),
    title: '新产品发布会即将召开',
    subtitle: '敬请期待最新产品系列',
    summary: '公司将于下月举办新产品发布会，敬请期待最新产品系列。',
    content: '<p>公司将于下月举办新产品发布会，敬请期待最新产品系列。</p><p>这是新闻的详细内容部分。</p>',
    cover_image: '',
    author: '市场部',
    source: '公司官网',
    keywords: '新产品,发布会',
    is_top: false,
    is_recommended: true,
    is_hot: false,
    status: 'published',
    view_count: 920,
    category: { id: uuidv4(), name: '公司动态' },
    publish_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    created_at: new Date(Date.now() - 86400000 * 5).toISOString()
  },
  {
    id: uuidv4(),
    title: '行业数字化转型趋势分析',
    subtitle: '技术驱动未来',
    summary: '随着技术的不断发展，行业数字化转型已成为必然趋势。',
    content: '<p>随着技术的不断发展，行业数字化转型已成为必然趋势。</p><p>这是新闻的详细内容部分。</p>',
    cover_image: '',
    author: '分析师',
    source: '行业报告',
    keywords: '数字化转型,行业趋势',
    is_top: false,
    is_recommended: false,
    is_hot: true,
    status: 'published',
    view_count: 2340,
    category: { id: uuidv4(), name: '行业资讯' },
    publish_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    created_at: new Date(Date.now() - 86400000 * 3).toISOString()
  },
  {
    id: uuidv4(),
    title: '我司荣获年度最佳创新企业奖',
    subtitle: '创新驱动发展',
    summary: '在刚刚结束的行业颁奖典礼上，我司荣获年度最佳创新企业奖。',
    content: '<p>在刚刚结束的行业颁奖典礼上，我司荣获年度最佳创新企业奖。</p><p>这是新闻的详细内容部分。</p>',
    cover_image: '',
    author: '公关部',
    source: '行业媒体',
    keywords: '创新企业,奖项',
    is_top: false,
    is_recommended: true,
    is_hot: false,
    status: 'published',
    view_count: 1860,
    category: { id: uuidv4(), name: '媒体报道' },
    publish_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    created_at: new Date(Date.now() - 86400000 * 7).toISOString()
  },
  {
    id: uuidv4(),
    title: '与知名企业达成战略合作协议',
    subtitle: '携手共进，共创未来',
    summary: '公司与多家知名企业达成战略合作协议，共同推动行业发展。',
    content: '<p>公司与多家知名企业达成战略合作协议，共同推动行业发展。</p><p>这是新闻的详细内容部分。</p>',
    cover_image: '',
    author: '战略部',
    source: '公司官网',
    keywords: '战略合作,企业合作',
    is_top: false,
    is_recommended: false,
    is_hot: false,
    status: 'published',
    view_count: 680,
    category: { id: uuidv4(), name: '合作交流' },
    publish_at: new Date(Date.now() - 86400000 * 10).toISOString(),
    created_at: new Date(Date.now() - 86400000 * 10).toISOString()
  }
];

const mockProductCategories = [
  { id: uuidv4(), name: '电子产品', code: 'electronics', parent_id: null, level: 1, sort: 1, status: 'active', is_show: true, children: [] },
  { id: uuidv4(), name: '办公设备', code: 'office', parent_id: null, level: 1, sort: 2, status: 'active', is_show: true, children: [] },
  { id: uuidv4(), name: '家用电器', code: 'home', parent_id: null, level: 1, sort: 3, status: 'active', is_show: true, children: [] },
];

const mockNewsCategories = [
  { id: uuidv4(), name: '公司动态', code: 'company', parent_id: null, level: 1, sort: 1, status: 'active', is_show: true },
  { id: uuidv4(), name: '行业资讯', code: 'industry', parent_id: null, level: 1, sort: 2, status: 'active', is_show: true },
  { id: uuidv4(), name: '媒体报道', code: 'media', parent_id: null, level: 1, sort: 3, status: 'active', is_show: true },
  { id: uuidv4(), name: '合作交流', code: 'cooperation', parent_id: null, level: 1, sort: 4, status: 'active', is_show: true },
];

module.exports = {
  mockUsers,
  mockProducts,
  mockNews,
  mockProductCategories,
  mockNewsCategories
};