CREATE DATABASE IF NOT EXISTS `food_delivery` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE `food_delivery`;

CREATE TABLE IF NOT EXISTS `sys_user` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `username` varchar(50) NOT NULL COMMENT '用户名',
  `password` varchar(255) NOT NULL COMMENT '密码',
  `nickname` varchar(100) DEFAULT NULL COMMENT '昵称',
  `phone` varchar(20) DEFAULT NULL COMMENT '手机号',
  `email` varchar(100) DEFAULT NULL COMMENT '邮箱',
  `avatar` varchar(255) DEFAULT NULL COMMENT '头像',
  `role_type` int NOT NULL DEFAULT '1' COMMENT '角色类型:1商家,2店员,3骑手,4平台,5管理员',
  `merchant_id` bigint DEFAULT NULL COMMENT '商家ID',
  `store_id` bigint DEFAULT NULL COMMENT '店铺ID',
  `status` int NOT NULL DEFAULT '1' COMMENT '状态:0禁用,1正常',
  `last_login_ip` varchar(50) DEFAULT NULL COMMENT '最后登录IP',
  `last_login_time` datetime DEFAULT NULL COMMENT '最后登录时间',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_username` (`username`),
  KEY `idx_phone` (`phone`),
  KEY `idx_store_id` (`store_id`),
  KEY `idx_role_type` (`role_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统用户表';

CREATE TABLE IF NOT EXISTS `merchant` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_name` varchar(100) NOT NULL COMMENT '商家名称',
  `contact_name` varchar(50) DEFAULT NULL COMMENT '联系人',
  `contact_phone` varchar(20) DEFAULT NULL COMMENT '联系电话',
  `business_license` varchar(255) DEFAULT NULL COMMENT '营业执照',
  `food_service_license` varchar(255) DEFAULT NULL COMMENT '食品经营许可证',
  `status` int NOT NULL DEFAULT '1' COMMENT '状态:0禁用,1正常',
  `owner_id` bigint DEFAULT NULL COMMENT '拥有者用户ID',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商家表';

CREATE TABLE IF NOT EXISTS `store` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_name` varchar(100) NOT NULL COMMENT '店铺名称',
  `store_address` varchar(255) DEFAULT NULL COMMENT '店铺地址',
  `contact_phone` varchar(20) DEFAULT NULL COMMENT '联系电话',
  `longitude` varchar(50) DEFAULT NULL COMMENT '经度',
  `latitude` varchar(50) DEFAULT NULL COMMENT '纬度',
  `business_status` int NOT NULL DEFAULT '1' COMMENT '营业状态:0休息,1营业',
  `open_time` varchar(20) DEFAULT NULL COMMENT '开门时间',
  `close_time` varchar(20) DEFAULT NULL COMMENT '关门时间',
  `store_logo` varchar(255) DEFAULT NULL COMMENT '店铺logo',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本',
  PRIMARY KEY (`id`),
  KEY `idx_merchant_id` (`merchant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='店铺表';

CREATE TABLE IF NOT EXISTS `platform_auth` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `platform_type` int NOT NULL COMMENT '平台类型:1美团,2饿了么,3自营',
  `platform_store_id` varchar(100) DEFAULT NULL COMMENT '平台店铺ID',
  `platform_store_name` varchar(100) DEFAULT NULL COMMENT '平台店铺名称',
  `app_id` varchar(100) DEFAULT NULL COMMENT '应用ID',
  `app_secret` varchar(255) DEFAULT NULL COMMENT '应用密钥',
  `access_token` text COMMENT '访问令牌',
  `refresh_token` text COMMENT '刷新令牌',
  `expire_time` datetime DEFAULT NULL COMMENT '过期时间',
  `auth_url` varchar(500) DEFAULT NULL COMMENT '授权URL',
  `callback_url` varchar(500) DEFAULT NULL COMMENT '回调URL',
  `auth_status` int NOT NULL DEFAULT '0' COMMENT '授权状态:0未授权,1已授权,2已过期',
  `ext_info` text COMMENT '扩展信息',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本',
  PRIMARY KEY (`id`),
  KEY `idx_store_id` (`store_id`),
  KEY `idx_platform_type` (`platform_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='平台授权表';

CREATE TABLE IF NOT EXISTS `order_main` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `order_no` varchar(50) NOT NULL COMMENT '系统订单号',
  `platform_order_no` varchar(100) DEFAULT NULL COMMENT '平台订单号',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `merchant_id` bigint DEFAULT NULL COMMENT '商家ID',
  `platform_type` int NOT NULL COMMENT '平台类型:1美团,2饿了么,3自营',
  `platform_store_id` varchar(100) DEFAULT NULL COMMENT '平台店铺ID',
  `order_status` int NOT NULL DEFAULT '15' COMMENT '订单状态',
  `receive_type` int DEFAULT NULL COMMENT '接单类型:1自动,2手动',
  `receive_by` bigint DEFAULT NULL COMMENT '接单人ID',
  `receive_time` datetime DEFAULT NULL COMMENT '接单时间',
  `customer_name` varchar(50) DEFAULT NULL COMMENT '顾客姓名',
  `customer_phone` varchar(20) DEFAULT NULL COMMENT '顾客电话',
  `delivery_address` varchar(255) DEFAULT NULL COMMENT '配送地址',
  `longitude` varchar(50) DEFAULT NULL COMMENT '经度',
  `latitude` varchar(50) DEFAULT NULL COMMENT '纬度',
  `order_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '订单金额',
  `goods_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '商品金额',
  `delivery_fee` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '配送费',
  `package_fee` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '打包费',
  `discount_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '优惠金额',
  `paid_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '实付金额',
  `order_remark` varchar(500) DEFAULT NULL COMMENT '订单备注',
  `delivery_type` int DEFAULT NULL COMMENT '配送类型:1平台配送,2商家自配',
  `rider_id` bigint DEFAULT NULL COMMENT '骑手ID',
  `rider_name` varchar(50) DEFAULT NULL COMMENT '骑手姓名',
  `rider_phone` varchar(20) DEFAULT NULL COMMENT '骑手电话',
  `prepare_start_time` datetime DEFAULT NULL COMMENT '开始制作时间',
  `prepare_end_time` datetime DEFAULT NULL COMMENT '制作完成时间',
  `rider_take_time` datetime DEFAULT NULL COMMENT '骑手取餐时间',
  `delivery_start_time` datetime DEFAULT NULL COMMENT '开始配送时间',
  `delivery_end_time` datetime DEFAULT NULL COMMENT '配送完成时间',
  `complete_time` datetime DEFAULT NULL COMMENT '订单完成时间',
  `printed` int NOT NULL DEFAULT '0' COMMENT '是否打印:0否,1是',
  `print_count` int NOT NULL DEFAULT '0' COMMENT '打印次数',
  `last_print_time` datetime DEFAULT NULL COMMENT '最后打印时间',
  `has_after_sale` int NOT NULL DEFAULT '0' COMMENT '是否有售后:0否,1是',
  `ext_info` text COMMENT '扩展信息',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_no` (`order_no`),
  KEY `idx_platform_order_no` (`platform_order_no`),
  KEY `idx_store_id` (`store_id`),
  KEY `idx_order_status` (`order_status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单主表';

CREATE TABLE IF NOT EXISTS `order_detail` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `order_id` bigint NOT NULL COMMENT '订单ID',
  `order_no` varchar(50) NOT NULL COMMENT '订单号',
  `platform_goods_id` bigint DEFAULT NULL COMMENT '平台商品ID',
  `platform_goods_name` varchar(200) NOT NULL COMMENT '平台商品名称',
  `platform_spec_name` varchar(100) DEFAULT NULL COMMENT '平台规格名称',
  `mapped_goods_id` bigint DEFAULT NULL COMMENT '映射商品ID',
  `mapped_goods_name` varchar(200) DEFAULT NULL COMMENT '映射商品名称',
  `mapped_spec_name` varchar(100) DEFAULT NULL COMMENT '映射规格名称',
  `quantity` int NOT NULL COMMENT '数量',
  `unit_price` decimal(10,2) NOT NULL COMMENT '单价',
  `total_price` decimal(10,2) NOT NULL COMMENT '总价',
  `goods_remark` varchar(200) DEFAULT NULL COMMENT '商品备注',
  `goods_status` int NOT NULL DEFAULT '1' COMMENT '商品状态',
  `ext_info` text COMMENT '扩展信息',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本',
  PRIMARY KEY (`id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_order_no` (`order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单明细表';

CREATE TABLE IF NOT EXISTS `order_status_log` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `order_id` bigint NOT NULL COMMENT '订单ID',
  `order_no` varchar(50) NOT NULL COMMENT '订单号',
  `from_status` int DEFAULT NULL COMMENT '原状态',
  `to_status` int NOT NULL COMMENT '目标状态',
  `event_code` varchar(50) DEFAULT NULL COMMENT '事件编码',
  `event_name` varchar(50) DEFAULT NULL COMMENT '事件名称',
  `source_type` varchar(50) DEFAULT NULL COMMENT '来源类型',
  `source_name` varchar(50) DEFAULT NULL COMMENT '来源名称',
  `operator_id` bigint DEFAULT NULL COMMENT '操作人ID',
  `operator_name` varchar(50) DEFAULT NULL COMMENT '操作人名称',
  `operator_role` varchar(50) DEFAULT NULL COMMENT '操作人角色',
  `reason` varchar(500) DEFAULT NULL COMMENT '原因',
  `ext_info` text COMMENT '扩展信息',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_order_no` (`order_no`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单状态流转日志';

CREATE TABLE IF NOT EXISTS `store_goods` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `merchant_id` bigint DEFAULT NULL COMMENT '商家ID',
  `category_id` bigint DEFAULT NULL COMMENT '分类ID',
  `goods_name` varchar(100) NOT NULL COMMENT '商品名称',
  `goods_code` varchar(50) DEFAULT NULL COMMENT '商品编码',
  `goods_image` varchar(255) DEFAULT NULL COMMENT '商品图片',
  `description` varchar(500) DEFAULT NULL COMMENT '描述',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序',
  `status` int NOT NULL DEFAULT '1' COMMENT '状态:0下架,1上架',
  `ext_info` text COMMENT '扩展信息',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本',
  PRIMARY KEY (`id`),
  KEY `idx_store_id` (`store_id`),
  KEY `idx_category_id` (`category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='店铺商品表';

CREATE TABLE IF NOT EXISTS `goods_spec` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `goods_id` bigint NOT NULL COMMENT '商品ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `spec_name` varchar(100) NOT NULL COMMENT '规格名称',
  `spec_code` varchar(50) DEFAULT NULL COMMENT '规格编码',
  `price` decimal(10,2) NOT NULL COMMENT '价格',
  `cost_price` decimal(10,2) DEFAULT NULL COMMENT '成本价',
  `stock` int NOT NULL DEFAULT '-1' COMMENT '库存:-1无限',
  `status` int NOT NULL DEFAULT '1' COMMENT '状态:0禁用,1启用',
  `ext_info` text COMMENT '扩展信息',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本',
  PRIMARY KEY (`id`),
  KEY `idx_goods_id` (`goods_id`),
  KEY `idx_store_id` (`store_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品规格表';

CREATE TABLE IF NOT EXISTS `goods_mapping` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `merchant_id` bigint DEFAULT NULL COMMENT '商家ID',
  `platform_type` int NOT NULL COMMENT '平台类型',
  `platform_store_id` varchar(100) DEFAULT NULL COMMENT '平台店铺ID',
  `platform_goods_id` bigint DEFAULT NULL COMMENT '平台商品ID',
  `platform_goods_name` varchar(200) NOT NULL COMMENT '平台商品名称',
  `platform_spec_id` bigint DEFAULT NULL COMMENT '平台规格ID',
  `platform_spec_name` varchar(100) DEFAULT NULL COMMENT '平台规格名称',
  `mapped_goods_id` bigint DEFAULT NULL COMMENT '映射商品ID',
  `mapped_goods_name` varchar(200) DEFAULT NULL COMMENT '映射商品名称',
  `mapped_spec_id` bigint DEFAULT NULL COMMENT '映射规格ID',
  `mapped_spec_name` varchar(100) DEFAULT NULL COMMENT '映射规格名称',
  `match_type` int NOT NULL DEFAULT '0' COMMENT '匹配类型:0无,1缓存,2精确ID,3名称,4模糊',
  `match_rule` varchar(500) DEFAULT NULL COMMENT '匹配规则',
  `mapping_status` int NOT NULL DEFAULT '1' COMMENT '映射状态:0无效,1有效',
  `mapping_reason` varchar(500) DEFAULT NULL COMMENT '映射原因',
  `ext_info` text COMMENT '扩展信息',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本',
  PRIMARY KEY (`id`),
  KEY `idx_store_id` (`store_id`),
  KEY `idx_platform_type` (`platform_type`),
  KEY `idx_mapped_goods_id` (`mapped_goods_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品映射表';

CREATE TABLE IF NOT EXISTS `print_task` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `order_id` bigint NOT NULL COMMENT '订单ID',
  `order_no` varchar(50) NOT NULL COMMENT '订单号',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `print_type` int NOT NULL COMMENT '打印类型:1厨房单,2收银小票',
  `printer_sn` varchar(100) DEFAULT NULL COMMENT '打印机SN',
  `printer_name` varchar(100) DEFAULT NULL COMMENT '打印机名称',
  `template_code` varchar(50) DEFAULT NULL COMMENT '模板编码',
  `print_content` longtext COMMENT '打印内容',
  `copies` int NOT NULL DEFAULT '1' COMMENT '打印份数',
  `print_status` int NOT NULL DEFAULT '0' COMMENT '打印状态:0待发送,1已发送,2已打印,3失败',
  `send_time` datetime DEFAULT NULL COMMENT '发送时间',
  `print_time` datetime DEFAULT NULL COMMENT '打印时间',
  `print_result` varchar(500) DEFAULT NULL COMMENT '打印结果',
  `error_message` varchar(500) DEFAULT NULL COMMENT '错误信息',
  `retry_count` int NOT NULL DEFAULT '0' COMMENT '重试次数',
  `ext_info` text COMMENT '扩展信息',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本',
  PRIMARY KEY (`id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_order_no` (`order_no`),
  KEY `idx_store_id` (`store_id`),
  KEY `idx_print_status` (`print_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='打印任务表';

CREATE TABLE IF NOT EXISTS `after_sale` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `after_sale_no` varchar(50) NOT NULL COMMENT '售后单号',
  `order_id` bigint NOT NULL COMMENT '订单ID',
  `order_no` varchar(50) NOT NULL COMMENT '订单号',
  `platform_after_sale_no` varchar(100) DEFAULT NULL COMMENT '平台售后单号',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `merchant_id` bigint DEFAULT NULL COMMENT '商家ID',
  `platform_type` int NOT NULL COMMENT '平台类型',
  `after_sale_type` int NOT NULL COMMENT '售后类型:1退款,2退货退款,3换货',
  `after_sale_status` int NOT NULL DEFAULT '1' COMMENT '状态:1待处理,2处理中,3已同意,4已拒绝,5已完成',
  `apply_amount` decimal(10,2) NOT NULL COMMENT '申请金额',
  `approved_amount` decimal(10,2) DEFAULT NULL COMMENT '审批金额',
  `apply_reason` varchar(500) DEFAULT NULL COMMENT '申请原因',
  `apply_evidence` text COMMENT '申请凭证',
  `apply_user_id` bigint DEFAULT NULL COMMENT '申请人ID',
  `apply_time` datetime DEFAULT NULL COMMENT '申请时间',
  `process_user_id` bigint DEFAULT NULL COMMENT '处理人ID',
  `process_result` varchar(50) DEFAULT NULL COMMENT '处理结果',
  `process_remark` varchar(500) DEFAULT NULL COMMENT '处理备注',
  `process_time` datetime DEFAULT NULL COMMENT '处理时间',
  `platform_response` text COMMENT '平台响应',
  `ext_info` text COMMENT '扩展信息',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_after_sale_no` (`after_sale_no`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_order_no` (`order_no`),
  KEY `idx_store_id` (`store_id`),
  KEY `idx_after_sale_status` (`after_sale_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='售后表';

CREATE TABLE IF NOT EXISTS `audit_log` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `trace_id` varchar(64) DEFAULT NULL COMMENT '追踪ID',
  `business_type` varchar(50) NOT NULL COMMENT '业务类型',
  `business_id` bigint DEFAULT NULL COMMENT '业务ID',
  `business_no` varchar(100) DEFAULT NULL COMMENT '业务编号',
  `source_type` varchar(50) DEFAULT NULL COMMENT '来源类型',
  `source_name` varchar(50) DEFAULT NULL COMMENT '来源名称',
  `operator_id` bigint DEFAULT NULL COMMENT '操作人ID',
  `operator_name` varchar(50) DEFAULT NULL COMMENT '操作人名称',
  `operator_role` varchar(50) DEFAULT NULL COMMENT '操作人角色',
  `action` varchar(50) NOT NULL COMMENT '操作动作',
  `action_name` varchar(100) DEFAULT NULL COMMENT '操作名称',
  `from_status` int DEFAULT NULL COMMENT '原状态',
  `from_status_name` varchar(50) DEFAULT NULL COMMENT '原状态名称',
  `to_status` int DEFAULT NULL COMMENT '目标状态',
  `to_status_name` varchar(50) DEFAULT NULL COMMENT '目标状态名称',
  `detail` text COMMENT '详情',
  `request_ip` varchar(50) DEFAULT NULL COMMENT '请求IP',
  `user_agent` varchar(500) DEFAULT NULL COMMENT '用户代理',
  `operate_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
  `ext_info` text COMMENT '扩展信息',
  PRIMARY KEY (`id`),
  KEY `idx_trace_id` (`trace_id`),
  KEY `idx_business` (`business_type`, `business_id`),
  KEY `idx_business_no` (`business_type`, `business_no`),
  KEY `idx_operate_time` (`operate_time`),
  KEY `idx_operator_id` (`operator_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='审计日志表';

CREATE TABLE IF NOT EXISTS `daily_statistics` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `merchant_id` bigint DEFAULT NULL COMMENT '商家ID',
  `statistics_date` date NOT NULL COMMENT '统计日期',
  `platform_type` int DEFAULT NULL COMMENT '平台类型(空表示全部)',
  `order_count` int NOT NULL DEFAULT '0' COMMENT '订单数',
  `valid_order_count` int NOT NULL DEFAULT '0' COMMENT '有效订单数',
  `cancel_order_count` int NOT NULL DEFAULT '0' COMMENT '取消订单数',
  `refund_order_count` int NOT NULL DEFAULT '0' COMMENT '退款订单数',
  `total_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '订单总金额',
  `valid_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '有效金额',
  `cancel_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '取消金额',
  `refund_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '退款金额',
  `receive_count` int NOT NULL DEFAULT '0' COMMENT '接单数',
  `auto_receive_count` int NOT NULL DEFAULT '0' COMMENT '自动接单数',
  `manual_receive_count` int NOT NULL DEFAULT '0' COMMENT '手动接单数',
  `print_count` int NOT NULL DEFAULT '0' COMMENT '打印次数',
  `avg_delivery_time` decimal(10,2) DEFAULT NULL COMMENT '平均配送时间(分钟)',
  `avg_prepare_time` decimal(10,2) DEFAULT NULL COMMENT '平均制作时间(分钟)',
  `ext_info` text COMMENT '扩展信息',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_store_date` (`store_id`, `statistics_date`),
  KEY `idx_statistics_date` (`statistics_date`),
  KEY `idx_store_id` (`store_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='日统计表';

CREATE TABLE IF NOT EXISTS `goods_sales_stat` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `merchant_id` bigint DEFAULT NULL COMMENT '商家ID',
  `goods_id` bigint DEFAULT NULL COMMENT '商品ID',
  `goods_name` varchar(100) DEFAULT NULL COMMENT '商品名称',
  `spec_id` bigint DEFAULT NULL COMMENT '规格ID',
  `spec_name` varchar(100) DEFAULT NULL COMMENT '规格名称',
  `platform_type` int DEFAULT NULL COMMENT '平台类型',
  `statistics_date` date NOT NULL COMMENT '统计日期',
  `sales_quantity` int NOT NULL DEFAULT '0' COMMENT '销售数量',
  `sales_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '销售金额',
  `refund_quantity` int NOT NULL DEFAULT '0' COMMENT '退款数量',
  `refund_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '退款金额',
  `ext_info` text COMMENT '扩展信息',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_goods_date` (`store_id`, `goods_id`, `spec_id`, `statistics_date`),
  KEY `idx_statistics_date` (`statistics_date`),
  KEY `idx_store_id` (`store_id`),
  KEY `idx_goods_id` (`goods_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='菜品销量统计表';

INSERT INTO `sys_user` (`id`, `username`, `password`, `nickname`, `phone`, `role_type`, `merchant_id`, `store_id`, `status`) VALUES
(1, 'admin', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iAt6Z5E', '系统管理员', '13800138000', 5, NULL, NULL, 1),
(2, 'merchant', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iAt6Z5E', '测试商家', '13800138001', 1, 1, 1, 1),
(3, 'clerk', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iAt6Z5E', '测试店员', '13800138002', 2, 1, 1, 1),
(4, 'rider', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iAt6Z5E', '测试骑手', '13800138003', 3, NULL, NULL, 1);

INSERT INTO `merchant` (`id`, `merchant_name`, `contact_name`, `contact_phone`, `status`, `owner_id`) VALUES
(1, '美味餐饮连锁', '张老板', '13800138001', 1, 2);

INSERT INTO `store` (`id`, `merchant_id`, `store_name`, `store_address`, `contact_phone`, `longitude`, `latitude`, `business_status`, `open_time`, `close_time`) VALUES
(1, 1, '美味餐厅(中关村店)', '北京市海淀区中关村大街1号', '13800138001', '116.307629', '40.058359', 1, '09:00', '22:00'),
(2, 1, '美味餐厅(国贸店)', '北京市朝阳区国贸大厦B座', '13800138004', '116.460947', '39.915285', 1, '09:30', '22:30');

INSERT INTO `platform_auth` (`id`, `store_id`, `platform_type`, `platform_store_id`, `platform_store_name`, `auth_status`) VALUES
(1, 1, 1, 'MT10001', '美味餐厅(中关村店)-美团', 1),
(2, 1, 2, 'EL10001', '美味餐厅(中关村店)-饿了么', 1),
(3, 2, 1, 'MT10002', '美味餐厅(国贸店)-美团', 0);

INSERT INTO `store_goods` (`id`, `store_id`, `merchant_id`, `goods_name`, `sort_order`, `status`) VALUES
(1, 1, 1, '宫保鸡丁', 1, 1),
(2, 1, 1, '鱼香肉丝', 2, 1),
(3, 1, 1, '糖醋排骨', 3, 1),
(4, 1, 1, '麻婆豆腐', 4, 1),
(5, 1, 1, '米饭', 10, 1);

INSERT INTO `goods_spec` (`id`, `goods_id`, `store_id`, `spec_name`, `price`, `stock`, `status`) VALUES
(1, 1, 1, '小份', 28.00, -1, 1),
(2, 1, 1, '大份', 38.00, -1, 1),
(3, 2, 1, '小份', 25.00, -1, 1),
(4, 2, 1, '大份', 35.00, -1, 1),
(5, 3, 1, '标准', 48.00, -1, 1),
(6, 4, 1, '标准', 18.00, -1, 1),
(7, 5, 1, '小碗', 2.00, -1, 1),
(8, 5, 1, '大碗', 3.00, -1, 1);
