const ORDER_STATUS = {
  PENDING_LOCATION: 'PENDING_LOCATION',
  PENDING_ROUTE_PLAN: 'PENDING_ROUTE_PLAN',
  NAVIGATING: 'NAVIGATING',
  PENDING_TRACK_RECORD: 'PENDING_TRACK_RECORD',
  ARRIVED: 'ARRIVED',
  CANCELLED: 'CANCELLED',
  EXCEPTION: 'EXCEPTION',
};

const STATUS_NAMES = {
  [ORDER_STATUS.PENDING_LOCATION]: '待输入位置',
  [ORDER_STATUS.PENDING_ROUTE_PLAN]: '待路线规划',
  [ORDER_STATUS.NAVIGATING]: '导航执行中',
  [ORDER_STATUS.PENDING_TRACK_RECORD]: '待轨迹记录',
  [ORDER_STATUS.ARRIVED]: '已到达确认',
  [ORDER_STATUS.CANCELLED]: '已取消',
  [ORDER_STATUS.EXCEPTION]: '异常',
};

const ROLE_NAMES = {
  ADMIN: '系统管理员',
  USER: '用户',
  DRIVER: '司机',
  DISPATCHER: '调度员',
  OPERATOR: '运营',
  MAP_PROVIDER: '地图服务商',
};

const ROUTE_TYPES = {
  FASTEST: 'FASTEST',
  SHORTEST: 'SHORTEST',
  NO_HIGHWAY: 'NO_HIGHWAY',
  AVOID_TRAFFIC: 'AVOID_TRAFFIC',
};

const ROUTE_TYPE_NAMES = {
  [ROUTE_TYPES.FASTEST]: '最快路线',
  [ROUTE_TYPES.SHORTEST]: '最短路线',
  [ROUTE_TYPES.NO_HIGHWAY]: '不走高速',
  [ROUTE_TYPES.AVOID_TRAFFIC]: '躲避拥堵',
};

const EXCEPTION_TYPES = {
  LOCATION_DRIFT: 'LOCATION_DRIFT',
  ROUTE_DEVIATION: 'ROUTE_DEVIATION',
  DRIVER_REJECT: 'DRIVER_REJECT',
  ARRIVAL_NOT_CONFIRMED: 'ARRIVAL_NOT_CONFIRMED',
  MAP_CALLBACK_DELAY: 'MAP_CALLBACK_DELAY',
  API_FAILURE: 'API_FAILURE',
  DUPLICATE_SUBMIT: 'DUPLICATE_SUBMIT',
  TIMEOUT: 'TIMEOUT',
};

const EXCEPTION_TYPE_NAMES = {
  [EXCEPTION_TYPES.LOCATION_DRIFT]: '定位漂移',
  [EXCEPTION_TYPES.ROUTE_DEVIATION]: '路线偏离',
  [EXCEPTION_TYPES.DRIVER_REJECT]: '司机拒接',
  [EXCEPTION_TYPES.ARRIVAL_NOT_CONFIRMED]: '到达未确认',
  [EXCEPTION_TYPES.MAP_CALLBACK_DELAY]: '地图回调延迟',
  [EXCEPTION_TYPES.API_FAILURE]: '接口失败',
  [EXCEPTION_TYPES.DUPLICATE_SUBMIT]: '重复提交',
  [EXCEPTION_TYPES.TIMEOUT]: '超时',
};

const ACTION_TYPES = {
  SUBMIT_LOCATION: 'SUBMIT_LOCATION',
  APPROVE_ROUTE: 'APPROVE_ROUTE',
  REJECT_ROUTE: 'REJECT_ROUTE',
  REQUEST_MORE_INFO: 'REQUEST_MORE_INFO',
  REASSIGN: 'REASSIGN',
  START_NAVIGATION: 'START_NAVIGATION',
  PAUSE_NAVIGATION: 'PAUSE_NAVIGATION',
  RESUME_NAVIGATION: 'RESUME_NAVIGATION',
  SUBMIT_TRACK: 'SUBMIT_TRACK',
  CONFIRM_ARRIVAL: 'CONFIRM_ARRIVAL',
  CANCEL_ORDER: 'CANCEL_ORDER',
  REVOKE: 'REVOKE',
};

const STATE_TRANSITIONS = {
  [ORDER_STATUS.PENDING_LOCATION]: {
    allowedActions: [ACTION_TYPES.SUBMIT_LOCATION, ACTION_TYPES.CANCEL_ORDER],
    allowedRoles: ['USER', 'ADMIN'],
    nextStatus: ORDER_STATUS.PENDING_ROUTE_PLAN,
    responsibleRole: 'USER',
  },
  [ORDER_STATUS.PENDING_ROUTE_PLAN]: {
    allowedActions: [
      ACTION_TYPES.APPROVE_ROUTE,
      ACTION_TYPES.REJECT_ROUTE,
      ACTION_TYPES.REQUEST_MORE_INFO,
      ACTION_TYPES.REASSIGN,
      ACTION_TYPES.CANCEL_ORDER,
    ],
    allowedRoles: ['DISPATCHER', 'ADMIN', 'USER'],
    nextStatus: ORDER_STATUS.NAVIGATING,
    responsibleRole: 'DISPATCHER',
  },
  [ORDER_STATUS.NAVIGATING]: {
    allowedActions: [
      ACTION_TYPES.START_NAVIGATION,
      ACTION_TYPES.PAUSE_NAVIGATION,
      ACTION_TYPES.RESUME_NAVIGATION,
      ACTION_TYPES.SUBMIT_TRACK,
      ACTION_TYPES.CONFIRM_ARRIVAL,
      ACTION_TYPES.CANCEL_ORDER,
    ],
    allowedRoles: ['DRIVER', 'ADMIN', 'DISPATCHER'],
    nextStatus: ORDER_STATUS.PENDING_TRACK_RECORD,
    responsibleRole: 'DRIVER',
  },
  [ORDER_STATUS.PENDING_TRACK_RECORD]: {
    allowedActions: [
      ACTION_TYPES.SUBMIT_TRACK,
      ACTION_TYPES.CONFIRM_ARRIVAL,
      ACTION_TYPES.CANCEL_ORDER,
    ],
    allowedRoles: ['DRIVER', 'ADMIN', 'DISPATCHER', 'OPERATOR'],
    nextStatus: ORDER_STATUS.ARRIVED,
    responsibleRole: 'OPERATOR',
  },
  [ORDER_STATUS.ARRIVED]: {
    allowedActions: [],
    allowedRoles: [],
    nextStatus: null,
    responsibleRole: null,
  },
  [ORDER_STATUS.CANCELLED]: {
    allowedActions: [],
    allowedRoles: [],
    nextStatus: null,
    responsibleRole: null,
  },
  [ORDER_STATUS.EXCEPTION]: {
    allowedActions: [
      ACTION_TYPES.REASSIGN,
      ACTION_TYPES.CANCEL_ORDER,
    ],
    allowedRoles: ['ADMIN', 'DISPATCHER', 'OPERATOR'],
    nextStatus: null,
    responsibleRole: 'OPERATOR',
  },
};

const MESSAGE_TYPES = {
  TODO: 'TODO',
  NOTIFICATION: 'NOTIFICATION',
  WARNING: 'WARNING',
  SYSTEM: 'SYSTEM',
};

const REPORT_DIMENSIONS = {
  BY_STATUS: 'BY_STATUS',
  BY_ROLE: 'BY_ROLE',
  BY_DATE: 'BY_DATE',
  BY_EXCEPTION: 'BY_EXCEPTION',
};

module.exports = {
  ORDER_STATUS,
  STATUS_NAMES,
  ROLE_NAMES,
  ROUTE_TYPES,
  ROUTE_TYPE_NAMES,
  EXCEPTION_TYPES,
  EXCEPTION_TYPE_NAMES,
  ACTION_TYPES,
  STATE_TRANSITIONS,
  MESSAGE_TYPES,
  REPORT_DIMENSIONS,
};
