const ORDER_STATUSES = {
  PENDING_PICKUP: 'pending_pickup',
  RIDER_ASSIGNED: 'rider_assigned',
  RIDER_ACCEPTED: 'rider_accepted',
  ON_THE_WAY: 'on_the_way',
  ARRIVED: 'arrived',
  WEIGHING: 'weighing',
  WEIGHED: 'weighed',
  IN_TRANSIT: 'in_transit',
  ARRIVED_AT_CENTER: 'arrived_at_center',
  CENTER_RECEIVED: 'center_received',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
  DISPUTED: 'disputed'
};

const STATUS_TRANSITIONS = {
  [ORDER_STATUSES.PENDING_PICKUP]: [ORDER_STATUSES.RIDER_ASSIGNED, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.RIDER_ASSIGNED]: [ORDER_STATUSES.RIDER_ACCEPTED, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.RIDER_ACCEPTED]: [ORDER_STATUSES.ON_THE_WAY, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.ON_THE_WAY]: [ORDER_STATUSES.ARRIVED, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.ARRIVED]: [ORDER_STATUSES.WEIGHING, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.WEIGHING]: [ORDER_STATUSES.WEIGHED, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.WEIGHED]: [ORDER_STATUSES.IN_TRANSIT, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.IN_TRANSIT]: [ORDER_STATUSES.ARRIVED_AT_CENTER, ORDER_STATUSES.DISPUTED],
  [ORDER_STATUSES.ARRIVED_AT_CENTER]: [ORDER_STATUSES.CENTER_RECEIVED, ORDER_STATUSES.DISPUTED],
  [ORDER_STATUSES.CENTER_RECEIVED]: [ORDER_STATUSES.COMPLETED, ORDER_STATUSES.DISPUTED],
  [ORDER_STATUSES.DISPUTED]: [ORDER_STATUSES.COMPLETED, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.COMPLETED]: [],
  [ORDER_STATUSES.CANCELLED]: []
};

const STATUS_NAMES = {
  [ORDER_STATUSES.PENDING_PICKUP]: '待揽收',
  [ORDER_STATUSES.RIDER_ASSIGNED]: '已分配骑手',
  [ORDER_STATUSES.RIDER_ACCEPTED]: '骑手已接单',
  [ORDER_STATUSES.ON_THE_WAY]: '骑手正在赶来',
  [ORDER_STATUSES.ARRIVED]: '骑手已到达',
  [ORDER_STATUSES.WEIGHING]: '称重中',
  [ORDER_STATUSES.WEIGHED]: '称重完成',
  [ORDER_STATUSES.IN_TRANSIT]: '运往集散中心',
  [ORDER_STATUSES.ARRIVED_AT_CENTER]: '到达集散中心',
  [ORDER_STATUSES.CENTER_RECEIVED]: '集散中心签收',
  [ORDER_STATUSES.COMPLETED]: '已完成',
  [ORDER_STATUSES.CANCELLED]: '已取消',
  [ORDER_STATUSES.DISPUTED]: '存在异议'
};

const ROLE_PERMISSIONS = {
  resident: {
    can_view: [
      ORDER_STATUSES.PENDING_PICKUP,
      ORDER_STATUSES.RIDER_ASSIGNED,
      ORDER_STATUSES.RIDER_ACCEPTED,
      ORDER_STATUSES.ON_THE_WAY,
      ORDER_STATUSES.ARRIVED,
      ORDER_STATUSES.WEIGHING,
      ORDER_STATUSES.WEIGHED,
      ORDER_STATUSES.IN_TRANSIT,
      ORDER_STATUSES.ARRIVED_AT_CENTER,
      ORDER_STATUSES.CENTER_RECEIVED,
      ORDER_STATUSES.COMPLETED,
      ORDER_STATUSES.CANCELLED
    ],
    can_transition: {
      [ORDER_STATUSES.PENDING_PICKUP]: [ORDER_STATUSES.CANCELLED]
    }
  },
  rider: {
    can_view: [
      ORDER_STATUSES.PENDING_PICKUP,
      ORDER_STATUSES.RIDER_ASSIGNED,
      ORDER_STATUSES.RIDER_ACCEPTED,
      ORDER_STATUSES.ON_THE_WAY,
      ORDER_STATUSES.ARRIVED,
      ORDER_STATUSES.WEIGHING,
      ORDER_STATUSES.WEIGHED,
      ORDER_STATUSES.IN_TRANSIT
    ],
    can_transition: {
      [ORDER_STATUSES.PENDING_PICKUP]: [ORDER_STATUSES.RIDER_ACCEPTED],
      [ORDER_STATUSES.RIDER_ASSIGNED]: [ORDER_STATUSES.RIDER_ACCEPTED],
      [ORDER_STATUSES.RIDER_ACCEPTED]: [ORDER_STATUSES.ON_THE_WAY],
      [ORDER_STATUSES.ON_THE_WAY]: [ORDER_STATUSES.ARRIVED],
      [ORDER_STATUSES.ARRIVED]: [ORDER_STATUSES.WEIGHING],
      [ORDER_STATUSES.WEIGHING]: [ORDER_STATUSES.WEIGHED],
      [ORDER_STATUSES.WEIGHED]: [ORDER_STATUSES.IN_TRANSIT]
    }
  },
  center: {
    can_view: [
      ORDER_STATUSES.IN_TRANSIT,
      ORDER_STATUSES.ARRIVED_AT_CENTER,
      ORDER_STATUSES.CENTER_RECEIVED,
      ORDER_STATUSES.COMPLETED,
      ORDER_STATUSES.DISPUTED
    ],
    can_transition: {
      [ORDER_STATUSES.IN_TRANSIT]: [ORDER_STATUSES.ARRIVED_AT_CENTER],
      [ORDER_STATUSES.ARRIVED_AT_CENTER]: [ORDER_STATUSES.CENTER_RECEIVED, ORDER_STATUSES.DISPUTED]
    }
  },
  operator: {
    can_view: Object.values(ORDER_STATUSES),
    can_transition: {
      [ORDER_STATUSES.DISPUTED]: [ORDER_STATUSES.COMPLETED, ORDER_STATUSES.CANCELLED],
      [ORDER_STATUSES.CENTER_RECEIVED]: [ORDER_STATUSES.COMPLETED]
    }
  }
};

function canTransition(fromStatus, toStatus, role) {
  const permissions = ROLE_PERMISSIONS[role];
  if (!permissions) return false;

  const allowedTransitions = permissions.can_transition[fromStatus] || [];
  return allowedTransitions.includes(toStatus);
}

function validateTransition(fromStatus, toStatus, role) {
  const allowedFromStateMachine = STATUS_TRANSITIONS[fromStatus] || [];
  if (!allowedFromStateMachine.includes(toStatus)) {
    return { valid: false, reason: '状态机不允许此转换' };
  }

  if (!canTransition(fromStatus, toStatus, role)) {
    return { valid: false, reason: '角色权限不足' };
  }

  return { valid: true };
}

module.exports = {
  ORDER_STATUSES,
  STATUS_TRANSITIONS,
  STATUS_NAMES,
  ROLE_PERMISSIONS,
  canTransition,
  validateTransition
};
