import type { UserRole, CarStatus, InspectionStatus, AppointmentStatus, DepositStatus, ContractStatus, TransferStatus, SettlementStatus, ExceptionStatus } from '../../api/types';
import {
  LayoutDashboard,
  Car,
  ClipboardCheck,
  CalendarDays,
  Wallet,
  FileSignature,
  ArrowLeftRight,
  Receipt,
  AlertTriangle,
  Users,
  FileText,
  Settings,
} from 'lucide-react';

export interface NavItem {
  key: string;
  label: string;
  icon: React.ComponentType<{ className?: string }>;
  path: string;
  roles: UserRole[];
  children?: NavItem[];
}

export const NAV_ITEMS: NavItem[] = [
  {
    key: 'dashboard',
    label: '工作台',
    icon: LayoutDashboard,
    path: '/dashboard',
    roles: ['dealer', 'buyer', 'inspector', 'sales', 'customer_service', 'finance', 'admin'],
  },
  {
    key: 'cars',
    label: '车辆管理',
    icon: Car,
    path: '/cars',
    roles: ['dealer', 'sales', 'customer_service', 'admin'],
  },
  {
    key: 'inspections',
    label: '检测管理',
    icon: ClipboardCheck,
    path: '/inspections',
    roles: ['inspector', 'admin'],
  },
  {
    key: 'appointments',
    label: '预约管理',
    icon: CalendarDays,
    path: '/appointments',
    roles: ['buyer', 'sales', 'customer_service', 'admin'],
  },
  {
    key: 'deposits',
    label: '定金管理',
    icon: Wallet,
    path: '/deposits',
    roles: ['buyer', 'dealer', 'finance', 'admin'],
  },
  {
    key: 'contracts',
    label: '合同管理',
    icon: FileSignature,
    path: '/contracts',
    roles: ['buyer', 'dealer', 'sales', 'finance', 'admin'],
  },
  {
    key: 'transfers',
    label: '过户管理',
    icon: ArrowLeftRight,
    path: '/transfers',
    roles: ['dealer', 'finance', 'admin'],
  },
  {
    key: 'settlements',
    label: '结算管理',
    icon: Receipt,
    path: '/settlements',
    roles: ['dealer', 'finance', 'admin'],
  },
  {
    key: 'exceptions',
    label: '异常处理',
    icon: AlertTriangle,
    path: '/exceptions',
    roles: ['customer_service', 'admin'],
  },
  {
    key: 'users',
    label: '用户管理',
    icon: Users,
    path: '/users',
    roles: ['admin'],
  },
  {
    key: 'audit',
    label: '审计日志',
    icon: FileText,
    path: '/audit',
    roles: ['admin'],
  },
  {
    key: 'statistics',
    label: '数据统计',
    icon: LayoutDashboard,
    path: '/statistics',
    roles: ['admin', 'finance'],
  },
  {
    key: 'settings',
    label: '系统设置',
    icon: Settings,
    path: '/settings',
    roles: ['admin'],
  },
];

export const STATUS_LABELS: Record<string, Record<string, string>> = {
  car: {
    draft: '草稿',
    pending_inspection: '待检测',
    inspecting: '检测中',
    inspection_rejected: '检测驳回',
    pending_audit: '待审核',
    on_sale: '在售',
    locked: '已锁定',
    sold: '已售出',
    off_shelf: '已下架',
    exception: '异常',
  } as Record<CarStatus, string>,
  inspection: {
    draft: '草稿',
    submitted: '已提交',
    approved: '已通过',
    rejected: '已驳回',
  } as Record<InspectionStatus, string>,
  appointment: {
    pending: '待确认',
    confirmed: '已确认',
    completed: '已完成',
    cancelled: '已取消',
    no_show: '未到场',
  } as Record<AppointmentStatus, string>,
  deposit: {
    pending: '待支付',
    paid: '已支付',
    locked: '已锁定',
    refund_pending: '退款待审',
    refunded: '已退款',
    released_to_seller: '已释放给卖家',
    deducted: '已扣除',
  } as Record<DepositStatus, string>,
  contract: {
    draft: '草稿',
    pending_sign: '待签署',
    signed: '已签署',
    pending_payment: '待付款',
    paid: '已付款',
    completed: '已完成',
    cancelled: '已取消',
  } as Record<ContractStatus, string>,
  transfer: {
    pending: '待提交',
    submitted: '已提交',
    reviewing: '审核中',
    approved: '已通过',
    completed: '已完成',
    rejected: '已驳回',
  } as Record<TransferStatus, string>,
  settlement: {
    pending: '待结算',
    settled: '已结算',
    reconciled: '已对账',
    invoiced: '已开票',
  } as Record<SettlementStatus, string>,
  exception: {
    open: '待处理',
    investigating: '调查中',
    resolved: '已解决',
    closed: '已关闭',
  } as Record<ExceptionStatus, string>,
};

export const STATUS_COLORS: Record<string, Record<string, string>> = {
  car: {
    draft: 'bg-gray-100 text-gray-800',
    pending_inspection: 'bg-yellow-100 text-yellow-800',
    inspecting: 'bg-blue-100 text-blue-800',
    inspection_rejected: 'bg-red-100 text-red-800',
    pending_audit: 'bg-orange-100 text-orange-800',
    on_sale: 'bg-green-100 text-green-800',
    locked: 'bg-purple-100 text-purple-800',
    sold: 'bg-green-100 text-green-800',
    off_shelf: 'bg-gray-100 text-gray-800',
    exception: 'bg-red-100 text-red-800',
  } as Record<CarStatus, string>,
  inspection: {
    draft: 'bg-gray-100 text-gray-800',
    submitted: 'bg-blue-100 text-blue-800',
    approved: 'bg-green-100 text-green-800',
    rejected: 'bg-red-100 text-red-800',
  } as Record<InspectionStatus, string>,
  appointment: {
    pending: 'bg-yellow-100 text-yellow-800',
    confirmed: 'bg-blue-100 text-blue-800',
    completed: 'bg-green-100 text-green-800',
    cancelled: 'bg-gray-100 text-gray-800',
    no_show: 'bg-red-100 text-red-800',
  } as Record<AppointmentStatus, string>,
  deposit: {
    pending: 'bg-yellow-100 text-yellow-800',
    paid: 'bg-green-100 text-green-800',
    locked: 'bg-purple-100 text-purple-800',
    refund_pending: 'bg-orange-100 text-orange-800',
    refunded: 'bg-gray-100 text-gray-800',
    released_to_seller: 'bg-green-100 text-green-800',
    deducted: 'bg-red-100 text-red-800',
  } as Record<DepositStatus, string>,
  contract: {
    draft: 'bg-gray-100 text-gray-800',
    pending_sign: 'bg-yellow-100 text-yellow-800',
    signed: 'bg-blue-100 text-blue-800',
    pending_payment: 'bg-orange-100 text-orange-800',
    paid: 'bg-green-100 text-green-800',
    completed: 'bg-green-100 text-green-800',
    cancelled: 'bg-red-100 text-red-800',
  } as Record<ContractStatus, string>,
  transfer: {
    pending: 'bg-yellow-100 text-yellow-800',
    submitted: 'bg-blue-100 text-blue-800',
    reviewing: 'bg-purple-100 text-purple-800',
    approved: 'bg-green-100 text-green-800',
    completed: 'bg-green-100 text-green-800',
    rejected: 'bg-red-100 text-red-800',
  } as Record<TransferStatus, string>,
  settlement: {
    pending: 'bg-yellow-100 text-yellow-800',
    settled: 'bg-blue-100 text-blue-800',
    reconciled: 'bg-purple-100 text-purple-800',
    invoiced: 'bg-green-100 text-green-800',
  } as Record<SettlementStatus, string>,
  exception: {
    open: 'bg-red-100 text-red-800',
    investigating: 'bg-yellow-100 text-yellow-800',
    resolved: 'bg-green-100 text-green-800',
    closed: 'bg-gray-100 text-gray-800',
  } as Record<ExceptionStatus, string>,
};

export const ROLE_LABELS: Record<UserRole, string> = {
  dealer: '车商',
  buyer: '买家',
  inspector: '检测员',
  sales: '销售',
  customer_service: '客服',
  finance: '财务',
  admin: '管理员',
};

export const CAR_BRANDS: string[] = [
  '奥迪',
  '宝马',
  '奔驰',
  '保时捷',
  '大众',
  '丰田',
  '本田',
  '日产',
  '马自达',
  '斯巴鲁',
  '雷克萨斯',
  '英菲尼迪',
  '讴歌',
  '凯迪拉克',
  '林肯',
  '福特',
  '雪佛兰',
  '别克',
  'Jeep',
  '特斯拉',
  '比亚迪',
  '蔚来',
  '小鹏',
  '理想',
  '问界',
  '极氪',
  '智己',
  '岚图',
  '红旗',
  '哈弗',
  '吉利',
  '长安',
  '奇瑞',
  '其他',
];
