#!/usr/bin/env bash
# 广州市统一政务服务移动端后端支撑平台
# 业务缺口可验证脚本 - API字段核验清单
# 用法：bash scripts/api-verification.sh
# 启动服务后执行：npm run start:dev

set -e

BASE="http://127.0.0.1:59207/api/v1/v1"
JWT=""

echo "===================================================="
echo "政务服务平台 API 业务字段核验清单"
echo "启动服务后执行此脚本：npm run start:dev"
echo "===================================================="
echo ""

echo "【0】登录获取 Token"
echo "  curl -sS '$BASE/auth/yueshengshi' \\"
echo "    -X POST -H 'Content-Type: application/json' \\"
echo "    -d '{\"code\":\"demo-code-20260616\"}' | head -c 800"
echo ""

echo "===================================================="
echo "【1】办件流转：6个业务动作 + 分支追溯"
echo "===================================================="
echo ""
echo "1.1 办件流转工作台（首屏Dashboard入口）"
echo "  GET '$BASE/admin/dashboard/overview'"
echo "  → 返回字段：topWorkEntries[?(@.entryCode=='workflow')].workbenchData"
echo "    .todayWorkflowActions[]              # 预约改期、材料补正、预审退回、部门会签、签发确认、结果回执"
echo "    .pendingReschedule                   # 待预约改期数"
echo "    .pendingSupplement                   # 待材料补正数"
echo "    .pendingOpinion                      # 待填审批意见数"
echo "    .pendingConfirmation                 # 待签发确认数"
echo "    .pendingReceipt                      # 待结果回执数"
echo "    .recentActions[]                     # 最近流转操作记录"
echo ""

echo "1.2 办件分支追溯（补正/退回/会签/回执/改期）"
echo "  GET '$BASE/admin/applications/:id/branches'"
echo "  → 返回字段：WorkflowBranch[]"
echo "    .branchId                            # 分支ID"
echo "    .branchType                          # SUPPLEMENT|RETURN|JOINT_SIGN|RECEIPT|RESCHEDULE"
echo "    .branchTypeLabel                     # 类型标签"
echo "    .sourceNode → targetNode             # 分支源节点→目标节点"
echo "    .initiator, .initiatorDept           # 发起人及部门"
echo "    .branchOpinion                       # 分支意见"
echo "    .auditTrail[]                        # 分支完整审计轨迹"
echo ""

echo "1.3 办件节点操作按钮（列表行级）"
echo "  GET '$BASE/admin/lifecycle/:id/node-actions'"
echo "  → 返回字段："
echo "    .workflowNodeActions[]               # 当前节点可执行按钮"
echo "      .actionCode                        # RESCHEDULE|SUPPLEMENT|SUBMIT_OPINION|..."
echo "      .actionName                        # 按钮名称"
echo "      .actionType                        # primary|secondary|warning"
echo "      .endpoint                          # API端点"
echo "    .workflowNodeStatus                  # 节点进度/预计剩余时长"
echo "    .responsibilitySummary               # 当前经办人/部门/下一环节/期限压力"
echo "    .closureStatus                       # 闭环完整度评分 0-100"
echo ""

echo "===================================================="
echo "【2】生命周期追踪：行级深度数据"
echo "===================================================="
echo ""
echo "2.1 办件生命周期列表"
echo "  GET '$BASE/admin/lifecycle'"
echo "  → 每条记录（LifecycleTraceListItem）包含："
echo ""
echo "    ┌─ 超时预警单列展开 ──────────────────────────┐"
echo "    │ .timeoutWarning                              │"
echo "    │   .warningLevel(1|2|3) .warningLevelLabel    │"
echo "    │   .overdueHours          .disposalDeadline   │"
echo "    │   .disposalCountdownMinutes                  │"
echo "    │   .disposer / .disposerId / .disposerDept    │"
echo "    │   .retryableNotifications[] 可重发列表       │"
echo "    └──────────────────────────────────────────────┘"
echo ""
echo "    ┌─ 风险详情单列展开 ──────────────────────────┐"
echo "    │ .riskDetails[]                               │"
echo "    │   .riskType(TIMEOUT|NOTIFICATION_FAIL|...)   │"
echo "    │   .riskLevel .riskLevelLabel .description    │"
echo "    │   .owner .ownerDept .status                  │"
echo "    │   .actionItems[] 可执行动作                   │"
echo "    └──────────────────────────────────────────────┘"
echo ""
echo "    ┌─ 部门催办记录 ──────────────────────────────┐"
echo "    │ .supervisionRecords[]                        │"
echo "    │   .supervisor .supervisorDept                │"
echo "    │   .supervisedDept .supervisedNode            │"
echo "    │   .supervisionLevel .supervisionContent      │"
echo "    │   .responseStatus .responder .responseContent│"
echo "    │   .followUpCount .lastFollowUpAt              │"
echo "    └──────────────────────────────────────────────┘"
echo ""
echo "    ┌─ 通知重发追溯 ──────────────────────────────┐"
echo "    │ .notificationRetryTraces[]                   │"
echo "    │   .channelLabel .originalSentAt              │"
echo "    │   .originalFailureReason .retryCount          │"
echo "    │   .retryRecords[] 每次重试详情                │"
echo "    │   .finalStatus .canRetry .retryEndpoint       │"
echo "    └──────────────────────────────────────────────┘"
echo ""
echo "    ┌─ 申请人确认记录 ────────────────────────────┐"
echo "    │ .applicantConfirmation                       │"
echo "    │   .confirmed .confirmedAt .confirmMethod     │"
echo "    │   .confirmRemark .receiptNo                  │"
echo "    │   .confirmDeadline .confirmCountdownMinutes  │"
echo "    └──────────────────────────────────────────────┘"
echo ""
echo "    .deptApprovalOpinions[]    部门审批意见数组"
echo "    .responsibilityChain[]     完整责任链追溯"
echo "    .branchSummary             分支统计"
echo ""

echo "2.2 办件生命周期详情（完整闭环）"
echo "  GET '$BASE/admin/lifecycle/:id/detail'"
echo "  → 返回完整8维闭环："
echo "    基本信息 → 预约信息 → 材料信息 → 预审信息"
echo "    → 审批流程（含部门意见/签名/转办链）"
echo "    → 证照信息（含签发凭证/电子印章/二维码）"
echo "    → 结果推送（含回执/渠道/失败原因）"
echo "    → 通知留痕（短信/微信/小程序 送达明细）"
echo "    → 完整时间线 + timeoutDisposalChain（完整处置链路）"
echo "    → branchTrail（完整分支追溯链）"
echo ""

echo "===================================================="
echo "【3】事项标准化：行级深度数据 + 可复查模板明细"
echo "===================================================="
echo ""
echo "3.1 事项标准化增强列表"
echo "  GET '$BASE/admin/service-items'"
echo "  → 每条记录（ServiceItemEnhancedListItem）包含："
echo ""
echo "    ┌─ 办理时限 ──────────────────────────────────┐"
echo "    │ .handlingTimeLimitDetail                     │"
echo "    │   .legalLimitDays .promisedLimitDays         │"
echo "    │   .specialLimitDays .limitDescription        │"
echo "    │ .handlingTimeLimitBreakdown                  │"
echo "    │   .legalBreakdown[] .promisedBreakdown[]     │"
echo "    │   .delayedPenalty 超期处罚说明                │"
echo "    └──────────────────────────────────────────────┘"
echo ""
echo "    ┌─ 适用条件明细（行级展开）──────────────────┐"
echo "    │ .applicableConditionItems[]                  │"
echo "    │   .condition .conditionType .isMandatory     │"
echo "    │   .description 条件说明                       │"
echo "    └──────────────────────────────────────────────┘"
echo ""
echo "    ┌─ 表单字段版本 ──────────────────────────────┐"
echo "    │ .formFieldVersions                           │"
echo "    │   .currentSchemaVersion .versionChangesCount │"
echo "    │   .lastUpdatedAt                             │"
echo "    │ .formFieldChangeLog[] 最近10条变更            │"
echo "    │   .version .fieldName .changeType            │"
echo "    │   .changedBy .changedAt .reason              │"
echo "    └──────────────────────────────────────────────┘"
echo ""
echo "    ┌─ 材料电子化校验 ────────────────────────────┐"
echo "    │ .materialEVerification                       │"
echo "    │   .totalMaterials .electronicallyVerified    │"
echo "    │   .verificationPassRate .verificationFailCount│"
echo "    │ .materialVerificationHistory[] 最近10条       │"
echo "    │   .verifyId .materialName .result            │"
echo "    │   .verifier .verifiedAt .failReason          │"
echo "    └──────────────────────────────────────────────┘"
echo ""
echo "    ┌─ 模板复核记录 ──────────────────────────────┐"
echo "    │ .templateReviewRecords[] 最近5条              │"
echo "    │   .reviewId .reviewer .reviewDept            │"
echo "    │   .reviewedAt .result .score                 │"
echo "    │   .issues .comment                           │"
echo "    │ .templateReviewStats                         │"
echo "    │   .totalReviews .passRate .avgScore          │"
echo "    └──────────────────────────────────────────────┘"
echo ""
echo "    .materialsSummary              材料必要性统计"
echo "    .materialDetails[]             前5条材料明细"
echo "    .formTemplateVersion + .formTemplateActive 版本/启停"
echo "    .changeHistory + .lastReviewStatus 变更审核"
echo "    .standardizationReview         标准化复查结论"
echo ""

echo "3.2 模板复核记录明细（可复查入口）"
echo "  GET '$BASE/admin/service-items/:id/template-review-records'"
echo "  → 返回该事项所有模板复核记录"
echo ""

echo "===================================================="
echo "【4】身份认证：NFC降级替代核验 + 授权凭证 + 二次核验"
echo "===================================================="
echo ""
echo "4.1 身份认证链路监控"
echo "  GET '$BASE/admin/auth-chain/distribution'"
echo "  → 每种认证类型包含："
echo ""
echo "    ┌─ 社保卡NFC降级状态 ────────────────────────┐"
echo "    │ .degradationInfo(SOCIAL_CARD_NFC)            │"
echo "    │   .isDegraded .status .degradedSince          │"
echo "    │   .fallbackAuthTypes[] 可回退的替代核验方式    │"
echo "    │   .manualReviewEnabled 是否启用人工复核        │"
echo "    └──────────────────────────────────────────────┘"
echo ""
echo "    ┌─ 替代核验记录 ──────────────────────────────┐"
echo "    │ .alternativeVerification                     │"
echo "    │   .hasAlternative .alternativeTypes[]         │"
echo "    │   .fallbackChain[] 核验切换链路               │"
echo "    │   .recentSwitches[] 最近10条替代核验          │"
echo "    │   .averageSwitchLatency 平均切换延迟           │"
echo "    └──────────────────────────────────────────────┘"
echo ""
echo "    ┌─ 授权凭证签发 ──────────────────────────────┐"
echo "    │ .authorizationCredentials                    │"
echo "    │   .totalCredentials .activeCredentials        │"
echo "    │   .expiredCredentials .credentialTypes[]     │"
echo "    │   .recentCredentialIssues[] 最近签发记录      │"
echo "    │   .credentialVerificationCount 总核验次数      │"
echo "    └──────────────────────────────────────────────┘"
echo ""
echo "    ┌─ 高风险二次核验流水 ────────────────────────┐"
echo "    │ .highRiskSecondaryVerification                │"
echo "    │   .enabled .totalHighRiskVerifications        │"
echo "    │   .secondaryVerificationRate .passRate        │"
echo "    │   .pendingSecondaryVerifications 待核验数     │"
echo "    │   .recentVerifications[] 最近10条核验流水     │"
echo "    │   .highRiskItemList[] 高风险事项清单          │"
echo "    └──────────────────────────────────────────────┘"
echo ""
echo "    .failureReasons[]              失败原因Top5"
echo "    .manualReviewStats             人工复核统计"
echo "    .impactCount + .impactedApplications[] 降级影响办件"
echo ""

echo "4.2 降级核验相关API"
echo "  GET  '$BASE/admin/auth-chain/degradation-status'"
echo "  GET  '$BASE/admin/auth-chain/impacted-applications'"
echo "  GET  '$BASE/admin/auth-chain/manual-review-queue'"
echo "  POST '$BASE/admin/auth-chain/manual-review/:reviewId'"
echo "  POST '$BASE/admin/auth-chain/degradation/report'"
echo ""

echo "===================================================="
echo "【5】政策语料：发布复查 + 版本来源 + 问答质量复查"
echo "===================================================="
echo ""
echo "5.1 政策文件增强列表"
echo "  GET '$BASE/admin/policies'"
echo "  → 每条记录包含："
echo ""
echo "    ┌─ 发布审核 ──────────────────────────────────┐"
echo "    │ .publishAudit                                 │"
echo "    │   .auditStatus(DRAFT|PENDING|AUDITED|...)     │"
echo "    │   .auditor .auditedAt .auditOpinion           │"
echo "    │   .publishAuditor .publishedAt .publishRemark │"
echo "    │   .auditHistory[] 审核历史链路                 │"
echo "    └──────────────────────────────────────────────┘"
echo ""
echo "    ┌─ 版本来源 ──────────────────────────────────┐"
echo "    │ .versionOrigin                                │"
echo "    │   .sourceType(ORIGINAL|DERIVED|IMPORTED|...)  │"
echo "    │   .sourceTypeLabel .sourcePolicyId            │"
echo "    │   .derivedFrom .importBatch                   │"
echo "    │   .changeBaseVersion .versionChanges[] 变更对 │"
echo "    └──────────────────────────────────────────────┘"
echo ""
echo "    ┌─ 问答质量复查 ──────────────────────────────┐"
echo "    │ .qaQualityReview                              │"
echo "    │   .totalQas .reviewedQas .passRate            │"
echo "    │   .qualityScore 质量评分 0-100                 │"
echo "    │   .recentQualityReviews[] 最近10条质量复查     │"
echo "    │   .qualityIssuesByCategory[] 问题分类统计      │"
echo "    └──────────────────────────────────────────────┘"
echo ""
echo "    .trainingVerification        训练样本复核"
echo "    .structuredReviewStatus      结构化复核状态"
echo "    .publishRecords[]           发布记录"
echo "    .corpusReviewStatus + .corpusPublishStatus 语料复查/发布"
echo ""

echo "5.2 复查详情API"
echo "  GET  '$BASE/admin/policies/:id/publish-audit'   # 发布审核详情"
echo "  GET  '$BASE/admin/policies/:id/quality-reviews' # 问答质量复查记录"
echo "  POST '$BASE/admin/policies/:id/structured-review'"
echo "  POST '$BASE/admin/policies/:id/publish'"
echo ""

echo "===================================================="
echo "【6】开放平台 + 堵点分析：可核验明细"
echo "===================================================="
echo ""
echo "6.1 开放平台授权范围 + 异常调用"
echo "  GET '$BASE/admin/open-api/verifiable-authorizations'"
echo "  → 返回："
echo "    .verifiableAuthorizations"
echo "      .scopesByApp[]              每应用授权明细"
echo "        .authorizedScopes[]       授权scope列表"
echo "        .grantedAt / .lastUsedAt / .callCount"
echo "      .scopesUsageRank[]          scope使用排行"
echo "      .pendingAuthorizationReviews[] 待审核授权"
echo "    .verifiableExceptions"
echo "      .recentExceptions[]         最近50条异常明细"
echo "        .callId / .appName / .endpoint"
echo "        .errorCode / .errorMessage / .occurredAt"
echo "      .exceptionTypes[]           异常类型分布"
echo "      .hourlyExceptionTrend[]     24小时异常趋势"
echo ""

echo "6.2 堵点热力图 + 归因明细"
echo "  GET '$BASE/admin/bottleneck/verifiable-heatmap'"
echo "  → 返回："
echo "    .verifiableHeatmap"
echo "      .heatmapDataPoints[]        192个数据点(24h×8部门)"
echo "        .dept / .hour / .timeoutCount"
echo "        .totalCount / .timeoutRate"
echo "      .top10BottleneckPoints[]    Top10堵点时间点"
echo "      .bottleneckCorrelations[]   相关性统计分析(p值)"
echo "    .verifiableAttribution"
echo "      .attributionEvidences[]     归因证据(带置信度)"
echo "      .caseStudies[]              10个典型堵点案例"
echo ""

echo "===================================================="
echo "【7】首屏Dashboard：6张深度业务卡片"
echo "===================================================="
echo ""
echo "  GET '$BASE/admin/dashboard/overview'"
echo "  → 返回 6 张深度卡片（全部下沉到首屏）："
echo ""
echo "  .standardizationCard  办理时限分布/材料校验/表单版本/适用条件/抽查记录"
echo "  .lifecycleCard        超时处置/协同记录/处置过程/通知重发/送达明细/责任链"
echo "  .policyReviewCard     复查状态/复查记录/待复查政策"
echo "  .openApiCard          授权范围明细/异常调用/待审核授权"
echo "  .bottleneckCard       Top5堵点节点/Top5归因/热力图峰值"
echo "  .authDegradationCard  NFC降级状态/替代核验/二次核验/凭证签发"
echo ""
echo "  .latestApplications[] 每个办件包含：certificateNo(签发编号)/approvalOpinion"
echo "                         /deliveryReceipt(回执)/applicantConfirmed/confirmTime"
echo "                         /deptCollaborationCount(协同次数)/notificationDeliveryDetail(短信/微信/小程序明细)"
echo ""
echo "  .topWorkEntries[]     入口(流转/超时/模板/证照/审批/确认)都直接带 todayWorkflowActions[]"
echo "                         包含：预约改期/材料补正/预审退回/部门会签/签发确认/结果回执"
echo ""
echo "===================================================="
echo "验证完成"
echo "Swagger文档地址：http://127.0.0.1:59207/api/v1/docs"
echo "===================================================="
