export enum UserRole {
  PATIENT = 'PATIENT',
  DOCTOR = 'DOCTOR',
  PHARMACIST = 'PHARMACIST',
  CUSTOMER_SERVICE = 'CUSTOMER_SERVICE',
  ADMIN = 'ADMIN',
}

export enum ConsultationStatus {
  PENDING_ACCEPT = 'PENDING_ACCEPT',
  ACCEPTED = 'ACCEPTED',
  IN_PROGRESS = 'IN_PROGRESS',
  PRESCRIPTION_PENDING = 'PRESCRIPTION_PENDING',
  PRESCRIPTION_REVIEWING = 'PRESCRIPTION_REVIEWING',
  PRESCRIPTION_APPROVED = 'PRESCRIPTION_APPROVED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REJECTED = 'REJECTED',
  RETURNED = 'RETURNED',
  TIMEOUT = 'TIMEOUT',
}

export enum PrescriptionStatus {
  DRAFT = 'DRAFT',
  PENDING_REVIEW = 'PENDING_REVIEW',
  REVIEWING = 'REVIEWING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  RETURNED = 'RETURNED',
  DISPENSED = 'DISPENSED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentStatus {
  FROZEN = 'FROZEN',
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUND_PENDING = 'REFUND_PENDING',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  CANCELLED = 'CANCELLED',
}

export enum MessageType {
  TEXT = 'TEXT',
  IMAGE = 'IMAGE',
  FILE = 'FILE',
  FORM = 'FORM',
  SYSTEM = 'SYSTEM',
  VIDEO_CALL = 'VIDEO_CALL',
}

export enum AuditActionType {
  CONSULTATION_CREATE = 'CONSULTATION_CREATE',
  CONSULTATION_ACCEPT = 'CONSULTATION_ACCEPT',
  CONSULTATION_CANCEL = 'CONSULTATION_CANCEL',
  CONSULTATION_COMPLETE = 'CONSULTATION_COMPLETE',
  CONSULTATION_RETURN = 'CONSULTATION_RETURN',
  CONSULTATION_TIMEOUT = 'CONSULTATION_TIMEOUT',
  PRESCRIPTION_CREATE = 'PRESCRIPTION_CREATE',
  PRESCRIPTION_REVIEW = 'PRESCRIPTION_REVIEW',
  PRESCRIPTION_APPROVE = 'PRESCRIPTION_APPROVE',
  PRESCRIPTION_REJECT = 'PRESCRIPTION_REJECT',
  PRESCRIPTION_RETURN = 'PRESCRIPTION_RETURN',
  PAYMENT_FREEZE = 'PAYMENT_FREEZE',
  PAYMENT_UNFREEZE = 'PAYMENT_UNFREEZE',
  PAYMENT_COMPLETE = 'PAYMENT_COMPLETE',
  PAYMENT_REFUND = 'PAYMENT_REFUND',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  DATA_MODIFY = 'DATA_MODIFY',
  DATA_DELETE = 'DATA_DELETE',
}

export enum FollowUpStatus {
  PENDING = 'PENDING',
  SCHEDULED = 'SCHEDULED',
  SENT = 'SENT',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
}

export enum OrderStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  RETURNED = 'RETURNED',
}

export enum Department {
  INTERNAL_MEDICINE = 'INTERNAL_MEDICINE',
  SURGERY = 'SURGERY',
  PEDIATRICS = 'PEDIATRICS',
  OBSTETRICS_GYNECOLOGY = 'OBSTETRICS_GYNECOLOGY',
  DERMATOLOGY = 'DERMATOLOGY',
  OPHTHALMOLOGY = 'OPHTHALMOLOGY',
  OTORHINOLARYNGOLOGY = 'OTORHINOLARYNGOLOGY',
  PSYCHIATRY = 'PSYCHIATRY',
  TRADITIONAL_CHINESE_MEDICINE = 'TRADITIONAL_CHINESE_MEDICINE',
  DENTISTRY = 'DENTISTRY',
}

export enum NotificationType {
  CONSULTATION_NEW = 'CONSULTATION_NEW',
  CONSULTATION_ACCEPTED = 'CONSULTATION_ACCEPTED',
  CONSULTATION_CANCELLED = 'CONSULTATION_CANCELLED',
  CONSULTATION_COMPLETED = 'CONSULTATION_COMPLETED',
  CONSULTATION_TIMEOUT = 'CONSULTATION_TIMEOUT',
  PRESCRIPTION_NEW = 'PRESCRIPTION_NEW',
  PRESCRIPTION_APPROVED = 'PRESCRIPTION_APPROVED',
  PRESCRIPTION_REJECTED = 'PRESCRIPTION_REJECTED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
  FOLLOW_UP_REMINDER = 'FOLLOW_UP_REMINDER',
  MESSAGE_NEW = 'MESSAGE_NEW',
  SYSTEM = 'SYSTEM',
}

export enum ReviewAction {
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  RETURN = 'RETURN',
}
