export default defineAppConfig({
  pages: [
    'pages/home/index',
    'pages/access/index',
    'pages/services/index',
    'pages/tickets/index',
    'pages/mine/index',
    'pages/access-detail/index',
    'pages/ticket-detail/index',
    'pages/ticket-create/index',
    'pages/service-detail/index',
    'pages/orders/index',
    'pages/cart/index',
    'pages/property/index',
    'pages/visitor/index',
    'pages/kpi/index',
    'pages/devices/index',
    'pages/notifications/index',
    'pages/role-switch/index',
    'pages/provider-apply/index',
    'pages/help/index',
    'pages/settings/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#2E7CF6',
    navigationBarTitleText: '阳光花园',
    navigationBarTextStyle: 'white',
    backgroundColor: '#F5F7FA',
  },
  tabBar: {
    color: '#86909C',
    selectedColor: '#2E7CF6',
    backgroundColor: '#FFFFFF',
    borderStyle: 'white',
    list: [
      { pagePath: 'pages/home/index', text: '首页' },
      { pagePath: 'pages/access/index', text: '门禁' },
      { pagePath: 'pages/services/index', text: '服务' },
      { pagePath: 'pages/tickets/index', text: '工单' },
      { pagePath: 'pages/mine/index', text: '我的' },
    ],
  },
});
